### ISSUE TITLE
Add build/test triggering for every PR and on the master branch

### ISSUE THREAD

**Issue by mbrukman** [gojek/feast#102]
It would be nice to have automated build/test run for every GitHub PR to ensure that new proposed changes aren't breaking the build.

It's also not clear what are the set of commands needed to run to ensure that a proposed change is not breaking anything, particularly given that there is code in Java, Go, and Python in a single repo.

Running the following command from an unmodified `master` branch:

```
make build-java
```

fails with:

```
[ERROR] Errors: 
[ERROR]   KafkaFeatureRowDeserializerTest.feast.source.kafka.deserializer.KafkaFeatureRowDeserializerTest » SessionExpired
[ERROR] Tests run: 112, Failures: 0, Errors: 1, Skipped: 0
```

If we had a build status badge on the README.md file that I could see the latest build status, it would help me to understand that this is an existing and known flaky/broken test, and it would incentivize others to help fix or disable this test to get to a green build.

**Comment by zhilingc** [comment]
@mbrukman Thanks for trying even with the limited documentation, a quickstart is in the works (as suggested in #98). The badges are a good idea! 

We have automated (unit) testing happening for the java components [here](http://prow.feast.ai/), and PRs can't be merged in unless the tests pass, but it seems like sometimes the automated merging breaks the build :/

**Comment by woop** [comment]
Added a PR for the badge.
