### ISSUE TITLE
Spring boot CLI logs show up as JSON

### ISSUE THREAD

**Issue by syvlabs** [gojek/feast#104]
## Expected Behavior 
CLI logs show up in a human-readable format

## Current Behavior
CLI logs show up as JSON:
<img width="1280" alt="screen shot 2019-01-25 at 5 01 58 pm" src="https://user-images.githubusercontent.com/11819007/51735841-6a8f5280-20c3-11e9-9b55-ccb427dfde90.png">

## Steps to reproduce

1. `mvn clean compile`
2. `java -jar ./core/target/feast-core-0.1.0.jar`

### Specifications

- Version: 0.1.0
- Platform: Linux
- Subsystem: Debian

Thanks!

**Comment by zhilingc** [comment]
We have it in json format so that we can process the logs more easily in stackdriver, but fair point, it makes debugging offline pretty hard. Would it be preferable for the user to be able to choose the type of logs they want to see?

**Comment by woop** [comment]
Should log as human readable text by default after #120 .
