### ISSUE TITLE
Add ability to start job from yaml using python sdk

### ISSUE THREAD

**Issue by zhilingc** [gojek/feast#124]
**Is your feature request related to a problem? Please describe.**
Currently the python sdk only supports the running of jobs from a Importer, which cannot be created from a import spec.

**Describe the solution you'd like**
Either create a command to start a job from a given yaml file or create a new method to instantiate an Importer from a given import spec.

**Comment by woop** [comment]
I think we should probably have both.

- Apply a spec
- Load importer from file (reverse of dump)

**Comment by woop** [comment]
This issue isn't relevant any more due to changes in Feast 0.3.0.
