### ISSUE TITLE
Build failure in cloudbuild

### ISSUE THREAD

**Issue by pradithya** [gojek/feast#128]
## Expected Behavior 
Build successful in cloud build 

## Current Behavior
Build failure in cloud build due to test which start a docker container.

**Comment by zhilingc** [comment]
Is it because the tests include non-unit tests? Can we turn those off when conducting unit tests? We should actually still run tests when packaging in case the auto-merge breaks anything.

**Comment by pradithya** [comment]
Yes, I've updated the PR.
