### ISSUE TITLE
FeatureRow proto to wrap FeatureRowKey and FeatureRowMessage

### ISSUE THREAD

**Issue by baskaranz** [gojek/feast#13]
Since Feast should support the ingestion of data from Kafka topics (in the format of KV) using KafkaIO, the FeatureRow proto should be wrapped to have FeatureRowKey (K) and FeatureRowMessage (V).

**Comment by woop** [comment]
@baskaranz can you propose an example of the proto format that you are suggesting? What would be contained within each of the FeatureRowKey and FeatureRowMessage?

**Comment by woop** [comment]
@baskaranz, I am assuming that this would replace the existing message format even for Pub/Sub, meaning this would be the new standard, right?

Does this impact Pub/Sub at all? If not, then the format looks fine to me. 

@tims, can you have a look?

**Comment by woop** [comment]
It seems like it's just for partitioning, so leaving it as null would be a valid approach, at least for now. @ravisuhag can you see any downsides?

Kafka issue: #22

**Comment by tims** [comment]
Can we close this now, I don't see a need to change FeatureRow to FeatureRowMessage. And we've already merged in a FeatureRowKey proto.

**Comment by woop** [comment]
We could close it, but are we happy leaving the code base as is. If we don't need FeatureRowKey, then shouldn't we remove it and add support for null keys during ingestion?

Or should that be a separate issue? @tims

**Comment by tims** [comment]
I'll add a note to the kafka source issue and close this one.
