### ISSUE TITLE
Listing resources and finding out system state

### ISSUE THREAD

**Issue by woop** [gojek/feast#131]
As far as I can see, both the Python SDK and the Feast CLI client only allows the users to take an action like registration of specifications, running jobs, or retrieving data.

One of the more basic challenges though, is figuring out
- Whether the client (SDK or CLI) is actually connected to Feast and whether the versions match
- Which specifications (features and entities) are registered

Do these commands exist, and if not, should we add them?

**Comment by woop** [comment]
I think I had an older version of the CLI. The current CLI does have the ability to list resources.

**Comment by tims** [comment]
Can we close this then? or what is missing that you'd like added? This good be a good first issue.

**Comment by woop** [comment]
There isnt feature parity, but lets pick this up later. Let's re-open at a later date.
