### ISSUE TITLE
Blocking call to start feast ingestion job

### ISSUE THREAD

**Issue by zhilingc** [gojek/feast#136]
**Is your feature request related to a problem? Please describe.**
It would be very useful to have the option to start an ingestion job in a blocking fashion, terminating only when the job has reached a terminal state. This is particularly helpful when starting jobs from an automated pipeline.

**Describe the solution you'd like**
This can be baked into the CLI/SDKs - just add an additional flag. The core API is fine as is since the get job endpoint returns the job state.

**Comment by tims** [comment]
Will this just poll for status on the client side?

**Comment by zhilingc** [comment]
Yep. I've implemented it on the CLI, will make the PR when i've tested it
