### ISSUE TITLE
Ability to correct mistakes made by ingesting the wrong data

### ISSUE THREAD

**Issue by baskaranz** [gojek/feast#139]
We should probably allow for **idempotent** writes and job ids:
- If a user now ingests data and makes a mistake, there's no way to undo/rollback and that data is in the warehouse permanently, and mixed in with other data. If we have a way to idempotently load data, or datasets, it would solve this problem. For example if a user provided the following job
    - Name: allocation-drivers
    - Version (date?): 20190101
Then Feast should replace the previous instance of that “20190101” version. The user should also be able to go and delete that dataset at that version.

**Comment by tims** [comment]
Can you update this to match the issue template?

**Comment by tims** [comment]
I need to see the proposal, but I'm concerned this will introduce inconsistencies with what is written to serving, we can't roll back the serving store.

**Comment by woop** [comment]
> I need to see the proposal, but I'm concerned this will introduce inconsistencies with what is written to serving, we can't roll back the serving store.

I think we should ignore serving for now, simply because it should be consistent eventually. If we rerun the ingestion job then it should fix serving, right?

**Comment by zhilingc** [comment]
Not necessarily. One such case is if the keys are different - you would still have records from the old job that weren't overwritten left in the store

**Comment by woop** [comment]
> Not necessarily. One such case is if the keys are different - you would still have records from the old job that weren't overwritten left in the store

That's true. Good point. 

I still think that the impact isn't as severe in serving as it is in the warehouse. It would mainly be for the cases where we have feature values set for entities where subsequent ingests don't overwrite those values.

**Comment by tims** [comment]
I've changed the title to be more of a user story

**Comment by tims** [comment]
@thirteen37 given the inception and work you've been doing, do we have a plan for this issue now?

**Comment by woop** [comment]
This issue isn't relevant any more due to changes in Feast 0.3.0. We will have immutable feature sets. Users will need to reingest data into feature sets in order to fix mistakes.
