### ISSUE TITLE
Ability to associate data ingested in Warehouse store to its ingestion job

### ISSUE THREAD

**Issue by baskaranz** [gojek/feast#145]
Currently, there isn’t a way to associate the data ingested in the warehouse store with the job that ingested it. This might make it hard for the users to identify the data sets of an ingestion job when/if erroneous data gets ingested or maybe to just investigate/explore the data ingested for a job.

**Comment by mansiib** [comment]
**Proposed solution:**
Adding an additional column to the warehouse, storing associated ingestion job identifier (job id). The job id will be added for each feature row ingested in the warehouse.

**Context**
This is one of the approaches to identify associated data with an ingestion job for the [Issue #139 ](https://github.com/gojek/feast/issues/139).

**Comment by tims** [comment]
Can we close this now?
