### ISSUE TITLE
Feast cli config file should be settable by an env var

### ISSUE THREAD

**Issue by tims** [gojek/feast#149]
**Is your feature request related to a problem? Please describe.**

If I have multiple feast instances, I want to be able to set different .feast files to configure the CLI.

**Describe the solution you'd like**

export FEAST_CONFIG=path/to/feast/configfile

it should default to ~/.feast

**Comment by woop** [comment]
This is a good issue. We can easily add a flag to the Python SDK to support this. For 0.3.0 the CLI is created from the SDK.

**Comment by woop** [comment]
Closing this since @accraze completed this task with #244
