### ISSUE TITLE
Default service type for Helm chart should not be LoadBalancer

### ISSUE THREAD

**Issue by davidheryanto** [gojek/feast#161]
## Expected Behavior 
Using **default** values in Feast Helm chart, the services created should **not** be of `LoadBalancer` type because users may **unintentionally expose** Feast services to the public internet.

> When service type is `LoadBalancer`, Kubernetes will usually assign an internal or external IP for the service. In Google Kubernetes Engine, a firewall rule will also be created to expose this service. This firewall rule use source `0.0.0.0/0` (all possible IPs). Hence, if this IP is external public facing IP, then this service is exposed to the public (which should not be the default)

## Current Behavior
The default service type is LoadBalancer:
- https://github.com/gojek/feast/blob/66464029c2ba0ca0cf8a8f215d6148b775620a43/charts/feast/templates/core-service.yaml#L14
- https://github.com/gojek/feast/blob/66464029c2ba0ca0cf8a8f215d6148b775620a43/charts/feast/templates/serving-service.yaml#L14

## Steps to reproduce
Deploy Feast with Helm using default values.

### Specifications
- Version: 0.0.2
- Platform: All platform

## Possible Solution
Make service type user configurable and set the default type to `ClusterIP`. It is also useful to provide examples and comments in the default values.yaml how user can provide the service type that they want and `loadBalancerSourceRanges` option they can provide. 

For example:
https://github.com/helm/charts/blob/ecb11fbf67208fa7334265c5347cca1b9bced522/incubator/jaeger/values.yaml#L130

**Comment by irvifa** [comment]
I wonder if there's a way to implements another object as an internal load balancer?

**Comment by woop** [comment]
This seems to be resolved: https://github.com/gojek/feast/blob/master/charts/feast/values.yaml#L21
