### ISSUE TITLE
"pip install Feast" does not work properly  

### ISSUE THREAD

**Issue by shihabuddinbuet** [gojek/feast#175]
Hi,
I'm having issue to install Feast using pip in host as well as container. I've tried in the following way to install in container:

```
$ docker pull python:3.7
$ docker run -it -d --name "feast" python:3.7
$ docker exec -it feast  bash
$ pip install Feast
$ python
>>> import feast
```
The error i'm getting :
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'feast'
```

The feast module is installed successfully and works fine if i install using "setup.py".

**Comment by zhilingc** [comment]
Hey, thanks for raising the issue! It looks like the problem is that we're missing the `__init__.py` files, which while is no longer required to define directories, is still required for packaging the modules.

Will make a PR and push a new version asap!

**Comment by zhilingc** [comment]
@shihabuddinbuet It should work now. The installed version should be `0.1.0.post0`

**Comment by shihabuddinbuet** [comment]
@zhilingc It is working now. Thanks for the update :) .
