### ISSUE TITLE
Quickstart.ipynb shows Description field cannot be empty

### ISSUE THREAD

**Issue by data-info-at-pathao-com** [gojek/feast#178]
## Expected Behavior 
While running Quickstart.ipynb pulled from lastest master it should ingest feature into Redis and Bigquery 

## Current Behavior

This shows error output in the console 

_Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.OUT_OF_RANGE
	details = "Validation for feature spec with id ride.log_trip_duration failed: Description field cannot be empty"
	debug_error_string = "{"created":"@1554898795.133803000","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1039,"grpc_message":"Validation for feature spec with id ride.log_trip_duration failed: Description field cannot be empty","grpc_status":11}"
## Steps to reproduce
- deploy feast 0.1.0 in kubernets 
- run quickstart.ipynb 

### Specifications

- Version: 0.1.0 
- Platform: macos 
- Subsystem:

## Possible Solution
Possibly quickstart.ipynb isn't updated

**Comment by woop** [comment]
This issue isn't relevant any more due to changes in Feast 0.3.0. We will be creating a new quickstart as part of that release.
