### ISSUE TITLE
Not able to push to feature store

### ISSUE THREAD

**Issue by dhillonr** [gojek/feast#192]
## Expected Behavior 
When using the Python SDK to ingest feature to feature store using Client,fs.run method should be able to apply features .
## Current Behavior
fs.run method returns an error:

---------------------------------------------------------------------------
_Rendezvous                               Traceback (most recent call last)
<ipython-input-22-3d0cbb8f1d02> in <module>
      1 # Ingest the feature data into the store
----> 2 fs.run(importer, apply_features=True, apply_entity=True)

~/.local/lib/python3.5/site-packages/feast/sdk/client.py in run(self, importer, name_override, apply_entity, apply_features)
    155 
    156         if apply_entity:
--> 157             self._apply_entity(importer.entity)
    158         if apply_features:
    159             for feature in importer.features:

~/.local/lib/python3.5/site-packages/feast/sdk/client.py in _apply_entity(self, entity)
    382         """
    383         self._connect_core()
--> 384         response = self._core_service_stub.ApplyEntity(entity.spec)
    385         if self.verbose:
    386             print(

~/.local/lib/python3.5/site-packages/grpc/_channel.py in __call__(self, request, timeout, metadata, credentials, wait_for_ready)
    560         state, call, = self._blocking(request, timeout, metadata, credentials,
    561                                       wait_for_ready)
--> 562         return _end_unary_response_blocking(state, call, False, None)
    563 
    564     def with_call(self,

~/.local/lib/python3.5/site-packages/grpc/_channel.py in _end_unary_response_blocking(state, call, with_call, deadline)
    464             return state.response
    465     else:
--> 466         raise _Rendezvous(state, None, None, deadline)
    467 
    468 

_Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Connect Failed"
	debug_error_string = "{"created":"@1557669015.402478394","description":"Failed to create subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":2715,"referenced_errors":[{"created":"@1557669015.402475745","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":456,"referenced_errors":[{"created":"@1557669015.402471734","description":"Connect Failed","file":"src/core/ext/filters/client_channel/subchannel.cc","file_line":963,"grpc_status":14,"referenced_errors":[{"created":"@1557669015.402450486","description":"Failed to connect to remote host: Connection refused","errno":111,"file":"src/core/lib/iomgr/tcp_client_posix.cc","file_line":207,"os_error":"Connection refused","syscall":"connect","target_address":"ipv4:127.0.0.1:8000"}]}]}]}"
>
## Steps to reproduce
In Quickstart.ipynb:

FEAST_CORE_URL = 'localhost:8000'
FEAST_SERVING_URL = 'localhost:8001'
STAGING_LOCATION = 'gs://test/abc/staging_location_feast'

fs = Client(core_url=FEAST_CORE_URL, verbose=True)

importer = Importer.from_df(df_complete, 
                           entity='ride',
                           owner='user@website.com',  
                           staging_location=STAGING_LOCATION,
                           id_column='ride', 
                           timestamp_column='pickup_datetime')

importer.entity.description = 'nyc taxi dataset' 
for feature_id in importer.features:
    importer.features[feature_id].description = 'nyc taxi dataset'

### Specifications

- Version:feast==0.1.0.post0
- Platform:Ubuntu 16.04
- Subsystem:

**Comment by woop** [comment]
Hi @dhillonr. Where is your Feast Core API running. Is it running locally on localhost:8000?

**Comment by woop** [comment]
Closing due to stale issue.
