### ISSUE TITLE
Add ability to check import job status and cancel job through python SDK

### ISSUE THREAD

**Issue by gracechristina** [gojek/feast#194]
Hi all,
As the import job is asynchronous, I cannot check whether the job has finished successfully or failed along the way through the python SDK. Cancelling running jobs is also not supported.

Therefore, I would like to propose these features in which we can:
1. Check the status of the job or start the job and wait for it to complete and get the result.
2. Cancel the running job.

One of the nice solution that I chance upon is the implementation in BigQuery load job python library:
https://googleapis.github.io/google-cloud-python/latest/bigquery/generated/google.cloud.bigquery.job.LoadJob.html

Thank you.

**Comment by woop** [comment]
Thanks @gracechristina. Moving this to 0.4.0

**Comment by woop** [comment]
This issue is now stale.
