### ISSUE TITLE
[FlinkRunner] Ingestion job tries to connect to every store available in core

### ISSUE THREAD

**Issue by zhilingc** [gojek/feast#20]
## Expected Behavior
Should only connect to the relevant stores specified in the FeatureSpec.

## Current Behavior
Will pull and attempt to connect to all the stores once the job is sent to the remote Flink cluster. If there are stores it cannot connect to, the entire job will fail.

## Steps to reproduce
- Register a storage that cannot be reached (e.g. 1.2.3.4:6379)
- Run a job (not using that store) on a remote flink cluster

## Possible Solution
Since we only pull specs at the graph building stage now, ingestion shouldn't have to retrieve and cache all available stores, only the stores it needs.

**Comment by tims** [comment]
You said that this is unrelated to ingestion... but ingestion calls on startup:

    specService.getAllStorageSpecs();

Even though it might not need them all. We could change this so that it only requests the serving and warehouse stores listed in the relevant feature specs if you like.

**Comment by tims** [comment]
Question though.. what is trying to connect to the stores? I didn't think that ingestion does if no features are using it. So is core doing that?

**Comment by zhilingc** [comment]
> I thought you said that this is unrelated to ingestion in a previous discussion... but ingestion calls on startup:
> 
> 
> ```
> specService.getAllStorageSpecs();
> ```
> Even though it might not need them all. We could change this so that it only requests the serving and warehouse stores listed in the relevant feature specs if you like. Is that the plan for this issue?

Yes, I think that is ideal. Also no: it is ingestion that fails if there is a store present in the registry that it cannot connect to. Are you able to replicate the error?
