### ISSUE TITLE
Entity & feature deletion

### ISSUE THREAD

**Issue by budi** [gojek/feast#202]
Bringing this one up again:

**Is your feature request related to a problem? Please describe.**
- Suppose I made a typo on feature or entity registration, there is no way for me to delete them through Feast (core/sdk)
- The current workaround is to delete the table manually in bq, then remove the metadata row in postgres

**Describe the solution you'd like**
`fs.delete_entity('entity name')` or `feast delete entity` on cli or a delete button on UI.. any of those would be better than the current situation.

**Describe alternatives you've considered**
This is tricky in a lot of ways:
- BQ doesn't support column deletion
- Currently there are no roles/authentication in Feast
- Instead of deletion, flagging features as `disabled` adds complexity in the long running ingestion jobs (will they continue ingesting?) or even serving (will they return values?), etc.

**Additional context**
- At least we should think about delete entity, as it would be useful in sandbox environment (to destroy and recreate). Currently our sandbox is filled with lots of typos and one-time ingestions

**Comment by woop** [comment]
This issue isn't relevant any more due to changes in Feast 0.3.0.
