### ISSUE TITLE
Fix Print Method in Feast CLI

### ISSUE THREAD

**Issue by davidheryanto** [gojek/feast#211]
## Expected Behavior 
Unit test in feast cli should pass every time

## Current Behavior
Example failure:
http://prow.feast.ai/view/gcs/feast-templocation-kf-feast/pr-logs/pull/gojek_feast/208/unit-test-cli/1138606091794386947

Unit test will fail occasionally. This is due to **mismatched expectation** between the actual functionality in the cli and the unit test. Test expects the printed output of the spec to be ordered but the cli data structure to store some values in spec data (i.e. map data structure) does not ensure order.

## Possible Solution
Either it's okay for the printed output of CLI to not be in order (in this case, the test case need to be updated) or modify the data structure used in CLI to store spec to support ordered iteration.

## Steps to reproduce
```
git clone https://github.com/gojek/feast
cd feast
# Need to run this command many times (e.g. 50 times) to observe the error 
go test -v ./cli/feast/...
```

### Specifications
- Version: 0.1.1 (https://github.com/gojek/feast/tree/d5000015f7313b8778d091138899cd6ddf9fd222)
- Platform: all

**Comment by woop** [comment]
This issue isn't relevant any more due to changes in Feast 0.3.0. The Feast CLI is being rewritten in Python.
