### ISSUE TITLE
Redis Error saying JedisConnectionException:connection timed out

### ISSUE THREAD

**Issue by quantum109678** [gojek/feast#219]
## Expected Behavior 
The batch import job should have been completed successfully

## Current Behavior
The job exits with an error code, throws the above mentioned error when the Dataflow was checked
## Steps to reproduce
Followed the steps in the install.md document

## Following is the exact error:
**java.lang.RuntimeException: org.apache.beam.sdk.util.UserCodeException: redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: connect timed out**

Also the command **gcloud redis instances list --region** does not list any instance

**Comment by davidheryanto** [comment]
I suspect your Redis instance setup is not successful.

In this section
https://github.com/gojek/feast/blob/master/docs/install.md#prepare-feast-cluster-and-redis-instance

There is this note:
> Comment out --no-address option if you do not have a NAT router set up in your project (especially in newly created Google Cloud Project). This will assign a public IP to the redis instance so it can access the internet without a NAT router. With no public IP, the instance requires a NAT router to access internet.

Can you try delete the existing Redis instance and re-run the gcloud command to create a virtual machine (VM) in Google Compute Engine (GCE) running redis server, but **remove --no-address** ?

Maybe your Google project do not have NAT router setup yet.

**Comment by davidheryanto** [comment]
Is this related to this issue #212

**Comment by quantum109678** [comment]
No, this is not related to that particular issue. Thanks for all the quick responses.

**Comment by woop** [comment]
Closing this since it is stale. I believe this will be resolved as part of 0.3. Lets reopen after the release if necessary.
