### ISSUE TITLE
Kafka source

### ISSUE THREAD

**Issue by tims** [gojek/feast#22]
The kafka IO PR #19 needs some follow ups.

* It appears to have broken the build? Or another merge removed an import. IOException symbol not found in ImportJob. 
* Import job gets google application default creds and uses options.setGcpCredential? Why? I've not needed to do that before if I set them in my environment. It would also seems odd to get an error logged about it if you're using the direct or flink runner and not using GCP at all.
* ImportJobOptions should not inherit FlinkPipelineOptions and GcpOptions, as that suggests it should always use Flink and GCP. These should already be registered by default, so you can just make use of them using options.as(GcpOptions.class) if needed.

**Comment by tims** [comment]
I also feel that the deserializer classes should be either inner classes or in a separate package with the feature row kafka IO class. As they are very kafka specific. But we can just move them when we get around to modularizing all the source classes.

**Comment by zhilingc** [comment]
I think i accidentally removed the IOException import when I did the merge, sorry :(

**Comment by tims** [comment]
I'm fixing it, pull request incoming

**Comment by tims** [comment]
@baskaranz

**Comment by tims** [comment]
I think we should also write an integration test before we close this issue.

**Comment by woop** [comment]
> I think we should also write an integration test before we close this issue.

I agree. Not having an integration test is part of the challenge. We merge based on trust that all relevant testing was done. Integration tests would remove that problem.

**Comment by baskaranz** [comment]
Tim, I can take it.

Thanks,
Baskaran

**Comment by tims** [comment]
@baskaranz any updates on this issue?

As discussed in #13. Can you also remove the FeatureRowKey proto message? We don't actually care what the key as everything is in the message, so we don't need it when reading. That's a concern for the publisher.

**Comment by zhilingc** [comment]
One more bug that I'd like to tag to this issue:

On the core side, the import spec validation prevents the submission of kafka jobs.

**Comment by baskaranz** [comment]
@woop apart from `Creation of unit tests for FeatureRowKafkaIO`, the rest of the items were taken care since there's an issue running the tests using FeatureRowKafkaIO.  I'm working with @pradithya on this. It works anyway, sauron uses it to read from feature stream. We can close this issue for now and open a new issue for `Creation of unit tests for FeatureRowKafkaIO`.
