### ISSUE TITLE
Does Feast help in feature engineering as a whole, i.e, calculating/ extracting the features or is this going to be developed in the near future?

### ISSUE THREAD

**Issue by quantum109678** [gojek/feast#220]
**Describe the solution you'd like**
A possibility of a tool or a service, which is integrated with Feast that helps in extracting or calculating features from the Data.

**Describe alternatives you've considered**
For now, the process of feature extraction and calculation is left to the Data Science team and Feast acts as a storage/access architecture is what I understand of Feast.

**Additional context**
If there is no provision for the above as of now, is it planned for a future release/version of Feast?

**Comment by woop** [comment]
Hi @quantum109678,

Feast 0.1 does not support transformations. We are open to adding that in the future, but that would be in 0.3 at the earliest. Right now we are trying to decompose the system to improve development speed (in 0.2).

**Comment by woop** [comment]
Closing this since it is informational.
