### ISSUE TITLE
Error when running feast apply entity integration-tests/testdata/entity_specs/entity_1.yaml

### ISSUE THREAD

**Issue by gogasca** [gojek/feast#226]
## Expected Behavior 
Running installation guide:

https://github.com/gojek/feast/blob/master/docs/install.md

## Current Behavior
Running from internal Google Corporate MacOSX (Google corporate wifi)
Running `feast apply entity integration-tests/testdata/entity_specs/entity_1.yaml` generates:

```
Applying entity at integration-tests/testdata/entity_specs/entity_1.yaml
Error: failed to apply entity at path integration-tests/testdata/entity_specs/entity_1.yaml: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 10.140.0.4:6565: i/o timeout"
Usage:
  feast apply [resource] [filepaths...] [flags]

Flags:
  -h, --help   help for apply
```

## Steps to reproduce

```
[feast_venv] ~/Documents/Development/dpe/feast master*$ kubectl get pod
NAME                             READY   STATUS    RESTARTS   AGE
feast-core-6cd8bd67f6-xrmqj      1/1     Running   1          11m
feast-postgresql-0               1/1     Running   0          11m
feast-serving-569fdc84df-sjt2t   1/1     Running   0          11m
[feast_venv] ~/Documents/Development/dpe/feast master*$ kubectl get svc --selector release=${FEAST_HELM_RELEASE_NAME} 
NAME                        TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                       AGE
feast-core                  LoadBalancer   10.63.243.66    10.140.0.4    80:31520/TCP,6565:32678/TCP   12m
feast-postgresql            ClusterIP      10.63.253.189   <none>        5432/TCP                      12m
feast-postgresql-headless   ClusterIP      None            <none>        5432/TCP                      12m
feast-serving               LoadBalancer   10.63.248.52    10.140.0.5    6565:30355/TCP,80:32549/TCP   12m
[feast_venv] ~/Documents/Development/dpe/feast master*$ FEAST_CORE_URI=10.140.0.4:6565
```
- Version: OSX
- Platform: Mac
- Subsystem: 

## Possible Solution

Tried from an instance in Cloud and same error.
```feast apply entity integration-tests/testdata/entity_specs/entity_1.yaml
Applying entity at integration-tests/testdata/entity_specs/entity_1.yaml
Error: failed to apply entity at path integration-tests/testdata/entity_specs/entity_1.yaml: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 10.140.0.4:6565: i/o timeout"
Usage:
  feast apply [resource] [filepaths...] [flags]

Flags:
  -h, --help   help for apply
```

**Comment by gogasca** [comment]
![image](https://user-images.githubusercontent.com/30065079/61833453-3229c080-ae29-11e9-950d-83a0754be6c3.png)

**Comment by gogasca** [comment]
![image](https://user-images.githubusercontent.com/30065079/61834471-f264d800-ae2c-11e9-957e-8a65b84b59ed.png)

**Comment by davidheryanto** [comment]
Hi @gogasca 
The dial timeout error seems like it is network issue. Can you help check if Feast service is actually reachable? e.g if you have `telnet` installed:
```bash
# Assuming FEAST_CORE_URI=10.140.0.4:6565
telnet 10.140.0.4 6565
# Should return "Connected to 10.140.0.4"
# If not, there may be access issue, 
# maybe due to the firewall configuration in GCP being too restrictive?
```

Alternatively, can you try accessing Feast pod directly, bypassing the Kubernetes service, by using port forwarding:
```bash
# the namespace where Feast is installed, default namespace is "default"
NAMESPACE=default

kubectl -n $NAMESPACE port-forward svc/feast-core 6565:6565
# Then you can use this value as FEAST_CORE_URI, and proceed as usual
# If you need to access the Feast serving, you can port-forward feast-serving too with a different local port number
FEAST_CORE_URI=localhost:6565
# Additionally, please check that now `telnet localhost 6565` should return "Connected"
```

**Comment by gogasca** [comment]
@davidheryanto thanks for responding will give it a try and get back to you.

**Comment by zhangjunqiang** [comment]
> Hi @gogasca
> The dial timeout error seems like a network issue (although your networks analysis screenshot looks ok). Can you help check if Feast service is actually reachable? e.g if you have `telnet` installed, run this command from the Feast client host:
> 
> ```shell
> # Assuming FEAST_CORE_URI=10.140.0.4:6565
> telnet 10.140.0.4 6565
> # Should return "Connected to 10.140.0.4"
> # If not, there may be access issue, 
> # maybe due to the firewall configuration in GCP being too restrictive?
> ```
> 
> Alternatively, can you try accessing Feast pod directly, bypassing the Kubernetes service, by using port forwarding:
> 
> ```shell
> # the namespace where Feast is installed, default namespace is "default"
> NAMESPACE=default
> 
> kubectl -n $NAMESPACE port-forward svc/feast-core 6565:6565
> # Then you can use this value as FEAST_CORE_URI, and proceed as usual
> FEAST_CORE_URI=localhost:6565
> 
> # Additionally, please check that now `telnet localhost 6565` should return "Connected"
> #
> # If you need to access Feast serving, you can port-forward feast-serving too 
> # with a different local port number
> ```

Hello, i have a some question with him.
i try it with port-forward is ok.
but with ingress is connection err.
here is my ingress yaml:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: feast-core-grpc
  namespace: test-feast
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: feast-core-grpc.service.com
    http:
      paths:
      - backend:
          serviceName: feast-core
          servicePort: 6565
  tls:
  - hosts:
    - feast-core-grpc.service.com
    secretName: grpc-secret

```

and i set the coreURI like :
feast config set coreURL feast-core-grpc.service.com

**Comment by woop** [comment]
Issue seems to be answered. @zhangjunqiang please create a new issue if needed.
