### ISSUE TITLE
dtype 'datetime64[ns, UTC]' importer fails because key looks like 'datetime64[ns, tz]'

### ISSUE THREAD

**Issue by bethrice44** [gojek/feast#229]
Expected behaviour:

Importer.from_bq() should detect 'datetime64[ns, UTC]' correctly and convert to ValueType TIMESTAMP

Current behaviour:

Importer.from_bq() is failing when the column dtype is detected as  'datetime64[ns, UTC]' (and any other specified timezone) since the dtype_to_value_type function  mapper defines the key as     "datetime64[ns, tz]": ValueType.TIMESTAMP.
 https://github.com/gojek/feast/blob/5f7ba6c06ef199ede49cdccd1c4f54781735a09b/sdk/python/feast/sdk/utils/types.py#L51

Possible Solution:

Convert 'datetime64[ns, UTC]' or any timezone to datetime64[ns] first since it casts to the same ValueType

**Comment by woop** [comment]
This has been merged into a later release than 0.1.2
