### ISSUE TITLE
Edit description in feature specification to also reflect in BigQuery schema description.

### ISSUE THREAD

**Issue by arfiadhi** [gojek/feast#239]
**Is your feature request related to a problem? Please describe.**
When editing of current existing feature-specification description to ingest feature into Bigquery table, the changes only reflected in Feast-Core page.

**Describe the solution you'd like**
Edit description and trigger CI to sync entity and feature specification should also change the description in Bigquery schema description. This can eliminate manual change in the BQ schema itself if a revision of current existing feature is needed.

**Comment by woop** [comment]
This makes sense @arfiadhi. It can possibly be picked up during 0.3.

**Comment by arfiadhi** [comment]
thanks, looking forward to it! @woop

**Comment by woop** [comment]
This feature is stale. Lets reopen if its still necessary given Feast 0.3 capabilities.
