### ISSUE TITLE
Can U replace jedis client to lettuce?

### ISSUE THREAD

**Issue by zhangjunqiang** [gojek/feast#247]
We use redis with cluster mode,so jedis cannot support pipeline？
I found that lettuce.io did this;
https://github.com/lettuce-io/lettuce-core/wiki/Pipelining-and-command-flushing
so can you replace jedis with lettuce?

**Comment by pradithya** [comment]
Both ingestion and serving uses jedis as client for single instance redis. I think it's possible to use lettuce for redis cluster mode but probably as separate serving storage type? WDYT @woop @zhilingc @davidheryanto  ?

**Comment by woop** [comment]
Is there a downside to using lettuce for even the single instance mode?

**Comment by pradithya** [comment]
Not that I am aware of. We could use lettuce for both single instance and cluster mode. It's just happen that RedisIO for Beam uses Jedis.

**Comment by woop** [comment]
Closing this issue and moving it to #478
