### ISSUE TITLE
Something about feature version

### ISSUE THREAD

**Issue by zhangjunqiang** [gojek/feast#248]
we have some cron job by feast importspec. I found that feature value is overwrite by redis. 
So when the import job of today is processing, the feature in the redis both have two version(feature of yesterday and feature of today).

Especially in some scenarios, for example, we have an offline model, the features that the model needs to use come from two entities. How do you ensure that the features acquired online are from the same version?

**Comment by woop** [comment]
@zhangjunqiang The data model in 0.1 only supports latest values in serving, but the values are being coalesced during ingestion. For 0.3, we are changing this model when converting features into groups called feature sets: http://bit.ly/feast-03-rfc

Here the sets always retain consistency within a row.

**Comment by zhangjunqiang** [comment]
> @zhangjunqiang The data model in 0.1 only supports latest values in serving, but the values are being coalesced during ingestion. For 0.3, we are changing this model when converting features into groups called feature sets: http://bit.ly/feast-03-rfc
> 
> Here the sets always retain consistency within a row.
thanks for your reply, but i cannot open the link you provide.

**Comment by zhangjunqiang** [comment]
thanks for yout reply~
but i cannot open the link you provide.

**Comment by zhangjunqiang** [comment]
> @zhangjunqiang The data model in 0.1 only supports latest values in serving, but the values are being coalesced during ingestion. For 0.3, we are changing this model when converting features into groups called feature sets: http://bit.ly/feast-03-rfc
> 
> Here the sets always retain consistency within a row.

Thanks for your reply~
but i cannot open the link you provide.

**Comment by woop** [comment]
> > @zhangjunqiang The data model in 0.1 only supports latest values in serving, but the values are being coalesced during ingestion. For 0.3, we are changing this model when converting features into groups called feature sets: http://bit.ly/feast-03-rfc
> > Here the sets always retain consistency within a row.
> 
> Thanks for your reply~
> but i cannot open the link you provide.

What does it say?

**Comment by woop** [comment]
This issue is now stale.
