### ISSUE TITLE
Metrics are not logged in statsd for requests with multiple features.

### ISSUE THREAD

**Issue by baskaranz** [gojek/feast#249]
## Expected Behaviour 
When a request to feast-serving has multiple features, all the features' metric should be logged in statsd.

## Current Behaviour
When queried for two features from feast-serving, only one of the feature's metric was logged in statsd.

## Steps to reproduce
Try querying from feast-serving with more than one features in the request.

### Specifications

- Version: 0.1.x
- Platform: all

**Comment by woop** [comment]
This is expired.
