### ISSUE TITLE
Error Store should not require a storage spec

### ISSUE THREAD

**Issue by zhilingc** [gojek/feast#27]
The error store should be defined on deployment (of core), and should not require a spec.

**Comment by zhilingc** [comment]
Currently my plan is to pass it in as 2 separate options:
`--errorsStoreType`: one of [`file.json`, `stderr`, `stdout`] - type of errors store to write to
`--errorsStoreOptions`: map of options for the errors store

is this ok @tims?

**Comment by tims** [comment]
That looks suspiciously like a storage spec :)

If we're committed to just files and logs.. we could just log to stderr by default if a file path isn't provided? 

I imagine we might want avro or parquet too though... hmm.

**Comment by tims** [comment]
I think json is ok, as long as it doesn't cause any shell escaping issues for the core api?

reviewing the rest now
