### ISSUE TITLE
No BQ projectId or datasetId in $FEAST_HOME/core/src/main/resources/application.yml (CONTRIBUTING.md)

### ISSUE THREAD

**Issue by NicholaiStaalung** [gojek/feast#295]
## Expected Behavior 
Being able to update BQ projectId and datasetId in ../core/../application.yml

## Current Behavior
Parameters are not present or not mnemonic in application.yml as described in CONTRIBUTING.md

From CONTRIBUTING.md
Note that you should change BigQuery projectId and datasetId accordingly
in "$FEAST_HOME/core/src/main/resources/application.yml"

## Steps to reproduce
git clone -b 0.3-dev https://github.com/gojek/feast
nano $FEAST_HOME/core/src/main/resources/application.yml
CTRL+W : projectId -> [ "projectId" not found ]
CTRL+W : datasetId -> [ "datasetId" not found ]

### Specifications

- Version: Feast 0.3-dev
- Platform: Localhost
- Subsystem: 

## Possible Solution
Add BQ parameters to ../core/../application.yml

**Comment by woop** [comment]
@NicholaiStaalung Good catch. The store information is now set in the application.yaml for the specific serving store, not Core any more.

We have refactored the configuration and will be merging it in today.

https://github.com/gojek/feast/pull/289/files#diff-755e8c6b38d8711ca34e14d4ee48b4fdR100

I will leave this issue open until we update the `CONTRIBUTING.md`

**Comment by NicholaiStaalung** [comment]
> @NicholaiStaalung Good catch. The store information is now set in the application.yaml for the specific serving store, not Core any more.
> 
> We have refactored the configuration and will be merging it in today.
> 
> https://github.com/gojek/feast/pull/289/files#diff-755e8c6b38d8711ca34e14d4ee48b4fdR100
> 
> I will leave this issue open until we update the `CONTRIBUTING.md`

Great stuff!

**Comment by woop** [comment]
Closing this since the document is fixed.

**Comment by woop** [comment]
https://docs.feast.dev/contributing
