### ISSUE TITLE
"Error: could not find tiller" from 0.3 install-feast.md instructions

### ISSUE THREAD

**Issue by NicholaiStaalung** [gojek/feast#301]
## Expected Behavior 
Start the feast pods from helm install

## Current Behavior
When following the instructions from https://github.com/gojek/feast/blob/0.3-dev/docs/getting-started/install-feast.md the error "Error: could not find tiller" when starting the feast pods in the minikube cluster

## Steps to reproduce
minikube start --cpus=3 --memory=4096 --kubernetes-version='v1.15.5'
export FEAST_IP=$(minikube ip)
export FEAST_CORE_URL=${FEAST_IP}:32090
export FEAST_SERVING_URL=${FEAST_IP}:32091
git clone https://github.com/gojek/feast.git
cd feast 
git checkout 0.3-dev
export FEAST_HOME_DIR=$(pwd) && cd infra/charts/feast
cp values-demo.yaml my-feast-values.yaml
sed -i "s/feast.example.com/${FEAST_IP}/g" my-feast-values.yaml
helm install --name feast -f my-feast-values.yaml .

### Specifications

- Version: 0.3-dev
- Platform: Localhost (minikube)
- Subsystem: helm 2.16.0, kubectl client 1.16.1, kubectl server 1.15.5, minikube 1.5.2

## Possible Solution
before "helm install --name feast -f my-feast-values.yaml ." add somthing similar to the following

kubectl apply -f tiller_config.yaml
helm init --service-account tiller --history-max 80

I have success starting the feast pods when using the instructions from feast 0.1 installation. I think the solution could be something similar

**Comment by woop** [comment]
Woah that is weird. I could have sworn I had the command there to install Tiller. It's as simple as `helm init`. The GKE installation at the bottom indicates it. I will update the Minikube docs.

Thanks for this @NicholaiStaalung

**Comment by woop** [comment]
Can you confirm that `helm init` works (without the service account)? 

https://github.com/gojek/feast/blob/0.3-dev/docs/getting-started/install-feast.md

**Comment by NicholaiStaalung** [comment]
> Can you confirm that `helm init` works (without the service account)?
> 
> https://github.com/gojek/feast/blob/0.3-dev/docs/getting-started/install-feast.md

It sure does. It even sets up the tiller pod faster than the approach i suggested :) Thanks
