### ISSUE TITLE
Could not update configuration file for Feast (Python sdk)

### ISSUE THREAD

**Issue by NicholaiStaalung** [gojek/feast#304]
## Expected Behavior 
Update configuration file for Feast Core (Python sdk)

## Current Behavior
After installing the python sdk (locally) with 
`pip install -e ${FEAST_HOME_DIR}/sdk/python`
and updating the URL's for Core with 
`feast config set core_url ${FEAST_CORE_URL}`
the error below occurs

> Could not update configuration file for Feast
> [Errno 20] Not a directory: '/home/nrs/.feast/config.toml'

## Steps to reproduce
Follow the steps 0 - 2 in https://github.com/gojek/feast/blob/0.3-dev/docs/getting-started/install-feast.md 
Checked for a successful system start with all pods running with 
`watch kubectl get pods`

Then running 
`pip3 install -e ${FEAST_HOME_DIR}/sdk/python --user`
`feast config set core_url ${FEAST_CORE_URL}`

I had to run `pip3` (not specified in installation) because feast requires python3.6 and i have multiple python versions

I had to assign the `--user` flag as i got a 'permision denied'. This could probably be a reason for the error but i dont know. 

### Specifications

- Version: 0.3-dev
- Platform: Localhost (minikube) on Ubuntu 18.04
- Subsystem: python 3.6.8,  helm 2.16.0, kubectl client 1.16.1, kubectl server 1.15.5, minikube 1.5.2

## Possible Solution
I checked for the .feast folder in my user folder and i showed a txt/plain file as you will see at the bottom. The file had the content 'coreURI: 34.77.157.189:6565' which is not an ip that i know.

I then tried removing the -e (editable) flag from the pip3 install command but then i got a ModuleNotFoundError for the cli
>Traceback (most recent call last):
>  File "/home/nrs/.local/bin/feast", line 5, in <module>
>   from cli import cli
>ModuleNotFoundError: No module named 'cli'

Im not sure i would suggest a solution to this. I think you might know better what might be the cause. Maybe the sdk is not properly updated as this is still a dev branch.

![image](https://user-images.githubusercontent.com/25878853/68748913-a1f0d080-05fd-11ea-8b7a-9042210e4dc0.png)
![image](https://user-images.githubusercontent.com/25878853/68748972-be8d0880-05fd-11ea-91a7-82c893cb0b1a.png)

**Comment by NicholaiStaalung** [comment]
Problem persists after master was updated to 0.3

**Comment by woop** [comment]
Hi @NicholaiStaalung 

Thanks for taking the effort to raise this. I have submitted the bug fix to the master branch. 

https://github.com/gojek/feast/commit/f6d6d8e6a3503c432bb7e830fbcc5179dcc7f476

Can you please use the master branch for installing the Python SDK and try again?

Thanks again :)

**Comment by NicholaiStaalung** [comment]
Hi @woop 

Yes, it's working now :) Im hitting another problem but ill open a new issue for that. Closing this one

**Comment by woop** [comment]
Great :)
