### ISSUE TITLE
Errors during kafka deserializer (passing) test execution

### ISSUE THREAD

**Issue by baskaranz** [gojek/feast#31]
Below error is thrown while running the kafka deserializer test, even though the test passes, which could break the build
`Caused by: java.io.FileNotFoundException: /var/folders/kd/yyfwdyk15b32xdjs1j9j3qsr0000gp/T/kafka-5510291321770207219/topic-3198cdeb-d825-4092-8c6d-bd27db077c5c-0/00000000000000000001.snapshot (No such file or directory)`

**Comment by tims** [comment]
Have you seen it break the build? or are you just seeing it in the logs?

**Comment by baskaranz** [comment]
@tims I was able to see some ERROR, apart from the WARN
`[pool-8-thread-1] **ERROR** kafka.server.LogDirFailureChannel - Error while renaming dir for topic-34cbe65a-091c-4ee0-b8a6-982fa88c8490-0 in dir /var/folders/1t/kbnrkxqd5p145rb2pf55h3_r0000gp/T/kafka-8236435894823362187
java.io.FileNotFoundException: /var/folders/1t/kbnrkxqd5p145rb2pf55h3_r0000gp/T/kafka-8236435894823362187/topic-34cbe65a-091c-4ee0-b8a6-982fa88c8490-0/00000000000000000001.snapshot (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)`

@zhilingc pointed out that it could be causing issue, so I addressed it.
