### ISSUE TITLE
Is BigQuery mandatory for Feast 0.3?

### ISSUE THREAD

**Issue by krajasek** [gojek/feast#319]
Hello @woop ,

We are running Kubeflow Pipelines 0.5 and are looking at using Feast as our feature store. Looking at the docs, it appears that BigQuery is used as the store for the feature data while Postgres is used to store feature metadata. Is there a hard dependency on BigQuery? Can we use any on-premise DB in its place to store the feature data? If so, can you please let us know how it can be done.

**Comment by woop** [comment]
Hi @krajasek, thank you for your interest!

This is the #1 most requested feature for Feast, and it's something we want to implement as soon as possible.

Right now BigQuery is a hard dependency. That being said, implementing another store should not be too difficult. Essentially there are two aspects to how the store is used.

1. When data is written into the store from the ingestion/load jobs.
2. When data is retrieved through the serving API.

For (1), adding a new store would mean just adding a new output destination. We are using Apache Beam for these jobs so it supports quite a few data stores. That being said, each store will have its own semantics and quirks on how to store data. Most relational databases should act similarly to BigQuery, and should not be hard to implement.

For (2), This requires a means to connect to the new store type and run SQL queries, it also requires a way to load data into the store (users currently provide entities for the query), and a way to export. For BigQuery we use GCS to load data into and out of the store. For another store type it could be different. This part will be a bit harder to impement.

So it will really depend on how soon you want to be up and running. If you are willing to wait a bit, we will pick this up eventually.

**Comment by krajasek** [comment]
Thanks @woop for the detailed explanation. We have an immediate need for a feature store and will come back to evaluation of Feast in the near future.

**Comment by woop** [comment]
> Thanks @woop for the detailed explanation. We have an immediate need for a feature store and will come back to evaluation of Feast in the near future.

Awesome. Good luck :)
