### ISSUE TITLE
AttributeError: 'FeatureSet' object has no attribute 'ingest'

### ISSUE THREAD

**Issue by NicholaiStaalung** [gojek/feast#323]
## Expected Behavior 
Ingest features from a Pandas DataFrame into a Feature Set

## Current Behavior
Im using the titanic dataset to test my local installation of Feast. When i follow the steps from https://github.com/gojek/feast/blob/master/docs/concepts.md "Data Model.Feature Set.Customer Transaction Example" it gives me the following error
> ---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-23-154c70e2d84d> in <module>
----> 1 pass_list.ingest(dataframe=df)

AttributeError: 'FeatureSet' object has no attribute 'ingest'

## Steps to reproduce
```
import feast
import pandas as pd
df = pd.read_csv(titanic.csv')
df.reset_index(inplace=True)
pass_list = feast.FeatureSet.from_yaml('passengers.yaml')
pass_list.ingest(dataframe=df)
```
### Specifications

- Version: 0.3 (master)
- Platform: Localhost (minikube), Ubuntu 18.04
- Subsystem: Python3.6.8

## Possible Solution
I looked through the https://github.com/gojek/feast/blob/master/sdk/python/feast/feature_set.py and couldnt find any ingest method. So maybe its hiding in a commit somewhere?

**Comment by woop** [comment]
@NicholaiStaalung Doc is out of date. It has moved to `client`.

```
client.ingest(my_feature_set, df)
```

**Comment by NicholaiStaalung** [comment]
> @NicholaiStaalung Apologies about that. The doc is out of date. It has moved to `client`.
> 
> ```
> client.ingest(my_feature_set, df)
> ```
> 
> Thanks for raising this! Will update the docs.

Thanks

**Comment by NicholaiStaalung** [comment]
@woop 
Maybe you should close it yourself when you have done the update. This is the reason for the reopening

**Comment by woop** [comment]
Done.
