### ISSUE TITLE
Unable to connect to postgres when installing feast into minikube

### ISSUE THREAD

**Issue by RukminiVS** [gojek/feast#342]
## Expected Behavior 
Feast should connect to postgres

## Current Behavior
Failing to connect to postgres

## Steps to reproduce
I have installed feast into minikube using https://github.com/gojek/feast/blob/master/docs/getting-started/install-feast.md

>>feast version
GetFeastCoreVersion failed with code "StatusCode.UNIMPLEMENTED"
Method feast.core.CoreService/GetFeastCoreVersion is unimplemented
{"sdk": {"version": "feast 0.3.0"}, "core": {"url": "192.168.99.117:32090", "version": "", "status": "not connected"}, "serving": {"url": "192.168.99.117:32091", "version": "0.3", "status": "connected"}}

>>kubectl get pods
NAME                                               READY   STATUS      RESTARTS   AGE
feast-feast-core-666856994d-x2znb                  1/1     Running     4          29m
feast-feast-serving-online-576d6f5c56-r55r9        1/1     Running     5          29m
feast-kafka-0                                      1/1     Running     1          29m
feast-kafka-1                                      1/1     Running     0          26m
feast-kafka-2                                      1/1     Running     0          25m
feast-kafka-config-3e860262-npsxc                  0/1     Completed   0          29m
feast-postgresql-0                                 1/1     Running     0          29m
feast-prometheus-statsd-exporter-9bcfb954b-g2f9p   1/1     Running     0          29m
feast-redis-master-0                               1/1     Running     0          29m
feast-zookeeper-0                                  1/1     Running     0          29m
feast-zookeeper-1                                  1/1     Running     0          27m
feast-zookeeper-2                                  1/1     Running     0          26m

>> mvn --projects core spring-boot:run
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.postgresql.core.PGStream.<init>(PGStream.java:61)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:144)

>>kubectl logs feast-postgresql-0 
postgresql 12:08:43.88
postgresql 12:08:43.88 Welcome to the Bitnami postgresql container
postgresql 12:08:43.88 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
postgresql 12:08:43.88 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
postgresql 12:08:43.88 Send us your feedback at containers@bitnami.com
postgresql 12:08:43.88
postgresql 12:08:43.89 INFO  ==> ** Starting PostgreSQL setup **
postgresql 12:08:43.92 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 12:08:43.93 INFO  ==> Loading custom pre-init scripts...
postgresql 12:08:43.93 INFO  ==> Initializing PostgreSQL database...
postgresql 12:08:43.94 INFO  ==> postgresql.conf file not detected. Generating it...
postgresql 12:08:43.94 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql 12:08:44.83 INFO  ==> Starting PostgreSQL in background...
postgresql 12:08:45.23 INFO  ==> Changing password of postgres
postgresql 12:08:45.24 INFO  ==> Configuring replication parameters
postgresql 12:08:45.27 INFO  ==> Configuring fsync
postgresql 12:08:45.28 INFO  ==> Loading custom scripts...
postgresql 12:08:45.28 INFO  ==> Enabling remote connections
postgresql 12:08:45.29 INFO  ==> Stopping PostgreSQL...
postgresql 12:08:46.30 INFO  ==> ** PostgreSQL setup finished! **

### Specifications

- Version: v0.3.0 tag release
- Platform: localhost (mac OSX)
- Subsystem: Python 3.7.5, minikube v1.5.2, kubectl client v1.16.1, kubectl server v1.15.5

**Comment by woop** [comment]
Hi @RukminiVS, 

Thank you so much for trying out Feast and for the feedback!

Where did you get this log/command from: `mvn --projects core spring-boot:run`?

Are you running it from outside Minikube?

**Comment by RukminiVS** [comment]
Hi woop,
I am following https://github.com/gojek/feast/blob/master/CONTRIBUTING.md.
Yes I am running outside minikube from feast home directory.
I want to verify serving and warehouse datastores and also want to experminent with creating feature sets.

**Comment by woop** [comment]
> Hi woop,
> I am following https://github.com/gojek/feast/blob/master/CONTRIBUTING.md.
> Yes I am running outside minikube from feast home directory.
> I want to verify serving and warehouse data stores and also want to experiment with creating feature sets.
> 
> Do I need to create service for postgres with NodePort and use that in $FEAST_HOME/core/src/main/resources/application.yml?

Hi @RukminiVS,

The contributing guide is purely for when you want to develop on the Feast code base, so if you only want to register feature sets then you already have everything you need.

You can just [install the feast client](https://github.com/gojek/feast/blob/master/docs/getting-started/install-feast.md) and set the `core_url` to your minikube Feast Core. It is already connected to Postgres it seems.

**Comment by RukminiVS** [comment]
Thanks woop.
Any example which I can follow?
Looks like https://github.com/gojek/feast/blob/master/sdk/python/examples/quickstart/Quickstart.ipynb is not updated for v0.3.x

**Comment by RukminiVS** [comment]
I see the same thing happening in https://github.com/gojek/feast/issues/318.
Now I could find https://github.com/gojek/feast/blob/feast-0-3-python-sdk-doc/sdk/python/docs/readme.md example.

**Comment by woop** [comment]
> Thanks @woop
> Any example which I can follow?
> Looks like https://github.com/gojek/feast/blob/master/sdk/python/examples/quickstart/Quickstart.ipynb is not updated for v0.3.x
> I have installed feast client and set core url.
> 
> I was able to fix connection issue, so editing the comment.
> 
> I am running following code:
> 
> import pandas as pd
> from feast.feature_set import FeatureSet
> from feast.entity import Entity
> from feast.client import Client
> 
> if **name** == "**main**":
> FEAST_CORE_URL = '192.168.99.120:32090'
> client = Client(core_url=FEAST_CORE_URL, verbose=True)
> customer_df = pd.read_csv('~/customer_data.csv')
> cust_trans_fs = FeatureSet.from_yaml('customer_transactions_feature_set.yaml')
> client.apply(cust_trans_fs)
> #client.ingest(cust_trans_fs, customer_df)
> 
> I am able to create feature set and 'feast feature-sets list' lists created feature set, but later when I do 'feast version' or try to ingest data into feature set I see that feast connection is lost.
> 
> > > feast version
> > > Connection timed out while attempting to connect to Feast Core gRPC server 192.168.99.120:32090

Hi @RukminiVS,

Thank you for your patience!

You are correct. That example is out of date. We have begun fleshing out more and more examples and documentation. 

Probably the easiest place to see the functionality right now is over here: https://github.com/gojek/feast/blob/master/tests/e2e/test_e2e.py#L77

Perhaps you can try to load features and then do retrieval?

**Comment by RukminiVS** [comment]
Hi @woop 
I missed replying. Thanks, the tests helped. I was able to create feature sets.

When i do client.ingest it says x rows ingested, but when i retrieve using get_online_features I see feature value comes blank.

**Comment by RukminiVS** [comment]
On a side note, how does feast decide if data should go to batch or online store as there is a single ingest method.

**Comment by RukminiVS** [comment]
Are there any plans to build UI for feast?

**Comment by woop** [comment]
> Are there any plans to build UI for feast?

Hell yes. In fact, we had one. Right now we are simply trying to stabilize "concepts" and overall architecture. When we are confident in those, we will spec out the UI.

**Comment by woop** [comment]
> Hi @woop
> I missed replying. Thanks, the tests helped. I was able to create feature sets.
> 
> When i do client.ingest it says x rows ingested, but when i retrieve using get_online_features I see feature value comes blank.
> X rows ingested is in finally so it is printed in case of failures too, ingest fails with following error:
> 
> Process Process-1:
> Traceback (most recent call last):
> File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
> self.run()
> File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 99, in run
> self._target(*self._args, **self._kwargs)
> File "/Users/r0v00cn/feast/sdk/python/feast/loaders/ingest.py", line 30, in _kafka_feature_row_chunk_producer
> producer = KafkaProducer(bootstrap_servers=brokers)
> File "/usr/local/lib/python3.7/site-packages/kafka/producer/kafka.py", line 381, in **init**
> **self.config)
> File "/usr/local/lib/python3.7/site-packages/kafka/client_async.py", line 240, in **init**
> self.config['api_version'] = self.check_version(timeout=check_timeout)
> File "/usr/local/lib/python3.7/site-packages/kafka/client_async.py", line 899, in check_version
> raise Errors.NoBrokersAvailable()
> kafka.errors.NoBrokersAvailable: NoBrokersAvailable

How much data did you ingest? This error typically means that no Kafka or Zookeeper is present. Sometimes the process exits if you dont provide enough disk space.

> On a side note, how does feast decide if data should go to batch or online store as there is a single ingest method.

It goes to all stores that subscribe to the feature set. Here is an [example](https://github.com/gojek/feast/blob/master/serving/sample_redis_config.yml) of a serving configuration with a subscription to all feature sets. It can be configured per serving deployment. Typically you would have a warehouse that subscribes to everything and a serving store that subscribes to as little as possible.

**Comment by RukminiVS** [comment]
> > Hi @woop
> > I missed replying. Thanks, the tests helped. I was able to create feature sets.
> > When i do client.ingest it says x rows ingested, but when i retrieve using get_online_features I see feature value comes blank.
> > X rows ingested is in finally so it is printed in case of failures too, ingest fails with following error:
> > Process Process-1:
> > Traceback (most recent call last):
> > File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
> > self.run()
> > File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 99, in run
> > self._target(*self._args, **self._kwargs)
> > File "/Users/r0v00cn/feast/sdk/python/feast/loaders/ingest.py", line 30, in _kafka_feature_row_chunk_producer
> > producer = KafkaProducer(bootstrap_servers=brokers)
> > File "/usr/local/lib/python3.7/site-packages/kafka/producer/kafka.py", line 381, in **init**
> > **self.config)
> > File "/usr/local/lib/python3.7/site-packages/kafka/client_async.py", line 240, in **init**
> > self.config['api_version'] = self.check_version(timeout=check_timeout)
> > File "/usr/local/lib/python3.7/site-packages/kafka/client_async.py", line 899, in check_version
> > raise Errors.NoBrokersAvailable()
> > kafka.errors.NoBrokersAvailable: NoBrokersAvailable
> 
> How much data did you ingest? This error typically means that no Kafka or Zookeeper is present. Sometimes the process exits if you dont provide enough disk space.

I have ingested 5 rows. But kafka pods show status as running.
> 
> > On a side note, how does feast decide if data should go to batch or online store as there is a single ingest method.
> 
> It goes to all stores that subscribe to the feature set. Here is an [example](https://github.com/gojek/feast/blob/master/serving/sample_redis_config.yml) of a serving configuration with a subscription to all feature sets. It can be configured per serving deployment. Typically you would have a warehouse that subscribes to everything and a serving store that subscribes to as little as possible.

Say I have 1 year data and all this belongs to a single feature set. Is there provision that says complete year's data goes to warehouse while just last 1 month's data goes to online store.
As per my understanding, there is only provision to specify feature set name and version as subscription in yaml.

**Comment by woop** [comment]
All data goes to both stores, but remember that the online store only stores the **latest values**. It does not store historical data. 

Does that solve your problem, or do you have a use case for historical data in online serving?

**Comment by RukminiVS** [comment]
Yes, it helps. Thanks @woop for clarifying my queries.

**Comment by woop** [comment]
Awesome, pleasure to have you here. We're still very actively working on this project. A lot coming soon!
