### ISSUE TITLE
No indications of values to be replaced in values.yaml for feast installation into cluster

### ISSUE THREAD

**Issue by NicholaiStaalung** [gojek/feast#350]
## Expected Behavior 
Being able to locate values to be replaced in feast/infra/charts/feast/values.yaml

## Current Behavior
From the GKE installation https://github.com/gojek/feast/blob/master/docs/getting-started/install-feast.md for feast paragraph 4 it says
![image](https://user-images.githubusercontent.com/25878853/70151088-6486dc80-16ab-11ea-8bbb-22eb221fa62c.png)

However, there are not commented fields (I think i can guess which ones) in values.yaml

Also, there are no occurences of `feast.example.com` in values.yaml to be replaced which i think is a mistake

(Probably you also should update the guide to use the master branch instead of 0.3-dev)

### Specifications

- Version: Master (0.3)
- Platform:
- Subsystem:

## Possible Solution
I have a feeling that the values.yaml files is in its entirety not the correct one to reference in the guide

**Comment by woop** [comment]
Hi @NicholaiStaalung, you are correct.

This should be pointing to the master branch. I don't know where the comments have gone to though. I will make sure to add them in. Lets leave this card open for now.

**Comment by NicholaiStaalung** [comment]
> Hi @NicholaiStaalung, you are correct.
> 
> This should be pointing to the master branch. I don't know where the comments have gone to though. I will make sure to add them in. Lets leave this card open for now.

Okay great. I can help test it when you have it done. Just ping me :)

**Comment by woop** [comment]
Awesome, thank you so much for your patience @NicholaiStaalung!
