### ISSUE TITLE
problem on helm install

### ISSUE THREAD

**Issue by yvendruscolo** [gojek/feast#352]
sorry for the blank issue, but the templates didn't seem to fit.

upon following the starting guide, when trying to run `helm install feast -f my-feast-values.yaml .`, i face myself with:
```
coalesce.go:165: warning: skipped value for image: Not a table.
```

not really sure what it means nor if its a relevant problem, but it may be the cause of the real issue: some pods never come up.

feast-kafka, feast-kafka-config, feast-prometheus-statsd-exporter, feast-redis-master and feast-zookeeper: alternate between ImagePullBackOff and ErrImagePull
feast-postgresql: keeps on Init:ErrImagePull

feast-feast-core, feast-feast-serving-batch and feast-feast-serving-online start running, then fall into Error and then CrashLoopBackOff

here is a snapshot of the state at about 10mins form running helm command:
```
NAME                                                READY   STATUS                  RESTARTS   AGE
feast-feast-core-6c6cd7dd6-ldvf5                    0/1     CrashLoopBackOff        6          10m
feast-feast-serving-batch-74c6799f76-c74d5          0/1     CrashLoopBackOff        6          10m
feast-feast-serving-online-6448c6cbf-25jmr          0/1     CrashLoopBackOff        6          10m
feast-kafka-0                                       0/1     ImagePullBackOff        0          10m
feast-kafka-config-403c108f-zlkcd                   0/1     ImagePullBackOff        0          10m
feast-postgresql-0                                  0/1     Init:ImagePullBackOff   0          10m
feast-prometheus-statsd-exporter-796c95c6f9-dbqjs   0/1     ImagePullBackOff        0          10m
feast-redis-master-0                                0/1     ImagePullBackOff        0          10m
feast-zookeeper-0                                   0/1     ImagePullBackOff        0          10m
```

**Comment by woop** [comment]
Hi @yvendruscolo. Thank you for your interest in the project!

Are you running this in Minikube? Could this perhaps be a connectivity problem? It looks like you arent able to retrieve some of these docker images.

We are using the following Kafka chart for example. Perhaps you should try and install that directly and just see if it works: https://github.com/confluentinc/cp-helm-charts/tree/master/charts/cp-kafka

**Comment by yvendruscolo** [comment]
indeed, that initially failed, and upon talking to my mates about cluster connectivity and inspecting network configs, we were able fully deploy this Kafka chart!
thank you for the attention and comprehension!
