### ISSUE TITLE
Unable to retrieve batch features from bigquery - Storage bucket not found (Docker Compose)

### ISSUE THREAD

**Issue by NicholaiStaalung** [gojek/feast#358]
## Expected Behavior 
Retrieve batch features from BigQuery

## Current Behavior
Error is 
> NotFound: 404 GET https://www.googleapis.com/storage/v1/b/your-gcp-project?projection=noAcl: Not Found 

Traceback
[tracebackBatchRet.txt](https://github.com/gojek/feast/files/3944701/tracebackBatchRet.txt)

## Steps to reproduce
Ingest data into bigquery via feast

Assign entity dataframe
`entity_df = host_df[["id"]].assign(datetime=datetime.utcnow())`

Assign feature id's
`feature_ids=[
        "filled_listings:2:price",
        "filled_listings:2:neighbourhood",
        "filled_listings:2:room_type"
]
`
Retrieve features
`batch_job = client.get_batch_features(feature_ids, entity_df)`

### Specifications

- Version: 0.3.2
- Platform: Local (Docker compose installation)
- Subsystem: 

## Possible Solution
From the NotFund error it looks like the URL to google cloud storage is incorrect -  It doesnt specify the correct project.

It could also be that there are no bucket to assign as staging location. I checked GCS in my project and no bucket was created.

**Comment by woop** [comment]
Hi @NicholaiStaalung,

Just want to confirm, did you fork and create a new .end file from [.env.sample](https://github.com/gojek/feast/blob/master/infra/docker-compose/.env.sample)?

If you did, can you confirm whether you modified the job staging location?

**Comment by NicholaiStaalung** [comment]
Hi @woop 

You are correct. I did not change the parameter when i copied .env.sample and modified parameters.

I could have guess it if i had looked more carefully through the file, but maybe the installation guide should include it. 

Some other feedback i have is to change 
`FEAST_JOB_STAGING_LOCATION=gs://your-gcp-project/bucket`
into 
`FEAST_JOB_STAGING_LOCATION=gs://your-gcp-project-bucket/staging-folder`
I made the mistake of not creating a folder in the bucket, which caused the avro file to be placed in a '/' folder which in return said that the entity df could be loaded into the store. Adding a staging folder manually and pointing to it in .env fixed it. 

Another thing. Sometimes batch ingestion to bigquery hangs at 100% and doesnt ingest the features. I have to interrupt the notebook. I think its because of the number of rows ingested as it happens for larger dataframes only. I cant ingest features again unless i do docker-compose down and up. Im guessing it could be a Beam problem, or maybe there are some restrictions to the docker container memory.  Ill open a separate issue if you say so, i just wanted your opinion?

**Comment by woop** [comment]
> Hi @woop
> 
> You are correct. I did not change the parameter when i copied .env.sample and modified parameters.
> 
> I could have guessed it if i had looked more carefully through the file, but maybe the installation guide should include it.
> 
> Some other feedback i have is to change
> `FEAST_JOB_STAGING_LOCATION=gs://your-gcp-project/bucket`
> into
> `FEAST_JOB_STAGING_LOCATION=gs://your-gcp-project-bucket/staging-folder`
> in the .env.sample file
> 
> I made the mistake of not creating a folder in the bucket, which caused the avro file to be placed in a '/' folder which in return said that the entity df couldnt be loaded into the store. Adding a staging folder manually and pointing to it in .env fixed it.
> 
> Another thing. Sometimes batch ingestion to bigquery hangs at 100% and doesnt ingest the features. I have to interrupt the notebook. I think its because of the number of rows ingested as it happens for larger dataframes only. I cant ingest features again unless i do docker-compose down and up. Im guessing it could be a Beam problem, or maybe there are some restrictions to the docker container memory. Ill open a separate issue if you say so, i just wanted your opinion?

I am pretty sure that is a Python client issue. Are you suing master? We ran into this issue today actually. It can be due to a subprocess being closed too early or the queue not being ready when ingestion starts. Multiprocessing in Python can be a little bit hairy. 

Are you able to reproduce the bug in a reliable way? If so, then I can take a look.

**Comment by NicholaiStaalung** [comment]
> > Hi @woop
> > You are correct. I did not change the parameter when i copied .env.sample and modified parameters.
> > I could have guessed it if i had looked more carefully through the file, but maybe the installation guide should include it.
> > Some other feedback i have is to change
> > `FEAST_JOB_STAGING_LOCATION=gs://your-gcp-project/bucket`
> > into
> > `FEAST_JOB_STAGING_LOCATION=gs://your-gcp-project-bucket/staging-folder`
> > in the .env.sample file
> > I made the mistake of not creating a folder in the bucket, which caused the avro file to be placed in a '/' folder which in return said that the entity df couldnt be loaded into the store. Adding a staging folder manually and pointing to it in .env fixed it.
> > Another thing. Sometimes batch ingestion to bigquery hangs at 100% and doesnt ingest the features. I have to interrupt the notebook. I think its because of the number of rows ingested as it happens for larger dataframes only. I cant ingest features again unless i do docker-compose down and up. Im guessing it could be a Beam problem, or maybe there are some restrictions to the docker container memory. Ill open a separate issue if you say so, i just wanted your opinion?
> 
> I am pretty sure that is a Python client issue. Are you suing master? We ran into this issue today actually. It can be due to a subprocess being closed too early or the queue not being ready when ingestion starts. Multiprocessing in Python can be a little bit hairy.
> 
> Are you able to reproduce the bug in a reliable way? If so, then I can take a look.

Yeah sure, ill open a new issue when i get the chance to look at it again.
