### ISSUE TITLE
Option to create a resource without overwriting existing records

### ISSUE THREAD

**Issue by zhilingc** [gojek/feast#37]
The core API currently only supports `apply` methods, which, if there is an existing resource with the same id, will update the existing record. There is no distinction between the response after creating a new resource vs. updating one.

There should be a way to `create` a resource - this action should fail if there is an existing resource already registered in the system.

We can either alter the existing `apply` method to take in an argument or add separate `create` methods.

**Comment by woop** [comment]
@zhilingc can you highlight the method you are referring to (for extension)?

**Comment by zhilingc** [comment]
From:
```rpc ApplyFeature(feast.specs.FeatureSpec) returns (CoreServiceTypes.ApplyFeatureResponse) {};```

To:
```
rpc ApplyFeature(CoreServiceTypes.ApplyFeatureRequest) returns (CoreServiceTypes.ApplyFeatureResponse) {};

message ApplyFeatureRequest {
  feast.specs.FeatureSpec spec = 1;
  bool update = 2;
}
```
I'm not sure if i prefer this method actually.

**Comment by woop** [comment]
This issue isn't relevant any more due to changes in Feast 0.3.0
