### ISSUE TITLE
K8S on GCP Readme is outdated

### ISSUE THREAD

**Issue by bruce3557** [gojek/feast#378]
## Expected Behavior
We should be able to run the command in readme to deploy feast on GKE.

## Current Behavior

* From the step `helm init --service-account tiller`, we cannot run the command because the flag --service-account is unsupported.
* `helm install --name feast -f my-feast-values.yaml . ` cannot work after helm v3

## Steps to reproduce
Run the command again

### Specifications

- Version: feast-0.3.2
- Platform: Mac

## Possible Solution
* For first issue, update the readme.
* For second issue, we can use helm install feast -f my-feast-valuies.yaml`.

**Comment by bruce3557** [comment]
also, I got the error when I try to connect core gRPC
```
GetFeastCoreVersion failed with code "StatusCode.UNIMPLEMENTED"
Method feast.core.CoreService/GetFeastCoreVersion is unimplemented
```

**Comment by woop** [comment]
Hi @bruce3557,

Thanks for creating the issue :)

I'll update the document by end of today.

**Comment by woop** [comment]
@bruce3557 Would it make sense to say we only support Helm v2 for now? I haven't personally tried out Helm 3 yet so I don't know how the API is different.

The `version` method is a bit of a pain, so I am removing that from the documentation.

**Comment by bruce3557** [comment]
I think that is ok.
I changed that to Helm v2 and it works with other issues.
I will open another issue and follow that~

Thanks a lot!
