### ISSUE TITLE
Batch ingestion hangs to bigquery (Docker compose)

### ISSUE THREAD

**Issue by NicholaiStaalung** [gojek/feast#379]
## Expected Behavior 
Ingest/update features to BigQuery

## Current Behavior
Process hangs at 100% without ingesting features to bigquery for approx 50k rows
![image](https://user-images.githubusercontent.com/25878853/71247883-f16f9e00-2319-11ea-9aff-6bc1627c65fe.png)

Im able to ingest features for a sub dataset (1500 rows) wihout any issues. Online ingestion and retrieval works like a charm.

## Steps to reproduce
Install feast via docker compose and start the services following [this](https://github.com/gojek/feast/blob/master/docs/getting-started/installing-feast.md) guide 

copy data into jupyter container (Im using a public dataset i have made public [here](https://storage.googleapis.com/feast-test/public/AB_NYC_2019.csv) )
`docker cp LOCAL/PATH/TO/AB_NYC_2019.csv JUPYTER_CONTAINERID:/home/jovyan/feast-notebooks/`

Get the yaml file from [here ](https://storage.googleapis.com/feast-test/public/AB_NYC_2019.yaml) an put it into the features folder

Go to http://localhost:8888/tree/feast-notebooks and run [this](https://storage.googleapis.com/feast-test/public/batch_ingestion.py) script
`python3 batch_ingestion.py`

The process hangs for me without ingestion to BQ

I tried running the feast-batch-serving notebook with 50k customers, and it ingests fine for that many rows.
### Specifications

- Version: feast 3.2 (docker-compose)
- Platform: (Ubuntu 18.04)
- Subsystem: 

## Possible Solution

**Comment by woop** [comment]
Hi @NicholaiStaalung 

Having a look at this now. I know we previously had a problem with ingestion getting blocked on some chipsets. Are you using the latest `master` branch?

**Comment by woop** [comment]
Out of curiousity, what happens when you use the Feast 0.3.4 SDK? I know that the ingestion logic has had some changes in the last two patches.

**Comment by khorshuheng** [comment]
@woop Feast 0.3.3 and latest should not have issue. The ingestion hangs because of a bug in Feast 0.3.2 Python SDK.

**Comment by NicholaiStaalung** [comment]
Upgrading to 0.3.4 solved the issue. Thanks @woop @khorshuheng
