### ISSUE TITLE
Toggle data stores using flags in feature specifications

### ISSUE THREAD

**Issue by woop** [gojek/feast#38]
I'm considering whether it is cleaner to have options within feature specifications like `useFeatureWarehouse: false` to enable or disable a specific type of storage option (serving, warehouse).

Thoughts?

Related to: #5

**Comment by tims** [comment]
This would help override and disable default stores. So I think this is nice.

**Comment by tims** [comment]
PR #39

**Comment by woop** [comment]
> This would help override and disable default stores. So I think this is nice.

Great. This is a classic `good first issue`, haha.

> PR #39 

How is this PR related?

**Comment by tims** [comment]
Ah oops.. it's not. I removed my comment.. but it's still linked. ah well.

**Comment by tims** [comment]
closing, wont fix, as we believe it would make more sense to configure stores with which features belong to them (in a future where we can deploy multiple serving stores with overlapping feature sets), than to configure the features.
