### ISSUE TITLE
Cannot deploy to kubernetes and execute feast version

### ISSUE THREAD

**Issue by bruce3557** [gojek/feast#396]
## Expected Behavior 
After deploying `values.yaml` on k8s, we can execute `feast version` to connect gRPC with the message.
```sh
{"sdk": {"version": "feast 0.3.2"}, "core": {"url": "localhost:6565", "version": "", "status": "connected"}, "serving": {"url": "localhost:6566", "version": "0.3", "status": "connected"}}
```

## Current Behavior
Now we will get the error on `GetFeastCoreVersion` with those message
```sh
GetFeastCoreVersion failed with code "StatusCode.UNIMPLEMENTED"
Method feast.core.CoreService/GetFeastCoreVersion is unimplemented
{"sdk": {"version": "feast 0.3.2"}, "core": {"url": "localhost:6565", "version": "", "status": "not connected"}, "serving": {"url": "localhost:6566", "version": "0.3", "status": "connected"}}
```

## Steps to reproduce
Follow the instruction here: https://docs.feast.dev/getting-started/installing-feast#google-kubernetes-engine

### Specifications

- Version: 0.3.2
- Platform: Kubernetes

## Possible Solution
Maybe need to add GetFeastCoreVersion on gRPC?

**Comment by bruce3557** [comment]
The interest thing is that I can execute the command of this file before ingestion https://github.com/gojek/feast/blob/master/examples/basic/basic.ipynb

but I will get ingestion error with the messages
```python
Ingestion started for customer_transactions:1
Process Process-14:
Traceback (most recent call last):
  File "/Users/bruce3557/.pyenv/versions/3.6.5/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Users/bruce3557/.pyenv/versions/3.6.5/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/bruce3557/git/bruce/feast/sdk/python/feast/loaders/ingest.py", line 50, in _kafka_feature_row_chunk_producer
    producer = KafkaProducer(bootstrap_servers=brokers)
  File "/Users/bruce3557/.local/share/virtualenvs/feast-8c5-fnhM/lib/python3.6/site-packages/kafka/producer/kafka.py", line 381, in __init__
    **self.config)
  File "/Users/bruce3557/.local/share/virtualenvs/feast-8c5-fnhM/lib/python3.6/site-packages/kafka/client_async.py", line 240, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/Users/bruce3557/.local/share/virtualenvs/feast-8c5-fnhM/lib/python3.6/site-packages/kafka/client_async.py", line 899, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable

Ingestion statistics:
Success: 0/155
  0%|                                                                                                                                                                             | 0/155 [00:00<?, ?rows/s]
```

**Comment by khorshuheng** [comment]
@bruce3557 
`GetFeastCoreVersion failed with code "StatusCode.UNIMPLEMENTED"
Method feast.core.CoreService/GetFeastCoreVersion is unimplemented
{"sdk": {"version": "feast 0.3.2"}, "core": {"url": "localhost:6565", "version": "", "status": "not connected"}, "serving": {"url": "localhost:6566", "version": "0.3", "status": "connected"}}`

This is a bug which we will fix, as the method has only been implemented for Feast Serving, but not Feast Core.

As for the Kafka broker not available error, is the Kafka broker reachable from the client? I am assuming that you deploy Kafka, Redis, Feast Core, Feast Serving on Kubernetes, but the client is running on local machine?

**Comment by bruce3557** [comment]
Yes, it seems workable after I use port-forward to local but not start feeding in server side.
Maybe some permission I didn't set them correct?

**Comment by woop** [comment]
Hi @bruce3557, is everything working for you now? Anything else that we can help with?

**Comment by woop** [comment]
Closing this since it is stale. @bruce3557, please let us know if you need any more help :)
