### ISSUE TITLE
Feast Logo

### ISSUE THREAD

**Issue by woop** [gojek/feast#413]
It's time that we create a logo for the project. For the time being I think we can get away with something simple.

Everyone is welcome to submit designs!

**Comment by woop** [comment]
No real movement here, so I'll be using the following logo for the time being.

![feast_logo_2020_05_23_full](https://user-images.githubusercontent.com/6728866/82723931-f8ee0580-9d04-11ea-80f7-7e4de04d5a59.png)


Happy to swap it out if somebody can contribute a better logo.

**Comment by ches** [comment]
Hehe I have been thinking about this issue since the move to dedicated org was looking sad. I have no opinion but anything is better than nothing 👍

**Comment by woop** [comment]
> Hehe I have been thinking about this issue since the move to dedicated org was looking sad. I have no opinion but anything is better than nothing

Yea I noticed you were proudly displaying the auto generated GitHub org icon on your profile :)
