### ISSUE TITLE
Deduplicate example notebooks

### ISSUE THREAD

**Issue by woop** [gojek/feast#415]
Currently we have two sets of example notebooks for Feast
1. [Examples](https://github.com/gojek/feast/tree/master/examples/basic)
2. [Docker compose](https://github.com/gojek/feast/tree/master/infra/docker-compose/jupyter/notebooks)

The docker compose notebooks can be deduplicated so that all examples are only contained in the root of the project. This would make management easier.

**Comment by napitupulus** [comment]
hi @woop, I used the latest master branch and it failed in ingestion when i run [Examples](https://github.com/gojek/feast/tree/master/examples/basic) outside `http://localhost:8888/tree/feast-notebooks`. 
So i tried to run it in `http://localhost:8888/tree/feast-notebooks` by changed the core-url and serving-url as in the [Docker compose](https://github.com/gojek/feast/tree/master/infra/docker-compose/jupyter/notebooks) and it works. 

Is it possible to run [Examples](https://github.com/gojek/feast/tree/master/examples/basic) outside the `http://localhost:8888/tree/feast-notebooks` ? so i wouldn't enter the `jupyter` container to ingest data into feast. Thankyou

**Comment by woop** [comment]
Hi @napitupulusThank you for being so patient.

Would it be possible to create a new issue perhaps? I dont think its on topic for this issue (deduplication of notebooks).

You should be able to run ingestion from outside Jupyter. I suspect that the problem is that you have a firewall blocking Kafka. The important part is that you expose the ingestion port from Kafka correctly. If you are unable to connect to the Kafka cluster then ingestion will fail.
