### ISSUE TITLE
Exclude documentation PRs from end-to-end tests

### ISSUE THREAD

**Issue by zhilingc** [gojek/feast#419]
## Expected Behavior 
Documentation PRs should not trigger end-to-end tests (or require them to be merged in)

## Possible Solution
Exclude the following from the prow configuration:
- .github
- docs
- README.md
- OWNERS
- CHANGELOG.md
- LICENSE

**Comment by ches** [comment]
Perhaps this could be picked up in tandem with #408, though it doesn't have to be, since this one is simpler.

**Comment by woop** [comment]
This is actually resolved already by #583. e2e is now manual.
