### ISSUE TITLE
Feast Roadmap

### ISSUE THREAD

**Issue by woop** [gojek/feast#420]
Creating this issue based on our conversations from the community call. We need to draft a roadmap for Feast for the next 6 months.

**Comment by woop** [comment]
Current roadmap for Feast 0.5 and Feast 0.6 has been documented [here](https://docs.google.com/document/d/1ZZY59j_c2oNN3N6TmavJIyLPMzINdea44CRIe2nhUIo/edit#).

**Comment by ches** [comment]
Should we have a more evergreen way to refer to this? The Google Doc isn't version-specific so that's fine as-is, but perhaps we can link to it from primary documentation so people can easily be aware of it.

Perhaps we could try to maintain [milestones in GitHub][1]? I see their are some project boards set up for release versions already, it's surprising that GitHub doesn't seem to have obvious ways yet to integrate projects and milestones with automation.

[1]: https://github.com/gojek/feast/milestones

**Comment by ches** [comment]
> Should we have a more evergreen way to refer to this? The Google Doc isn't version-specific so that's fine as-is, but perhaps we can link to it from primary documentation so people can easily be aware of it.

Sorry, I just noticed that it is linked on the README, but not on feast.dev GitBook I don't believe. Maybe it could be referenced on the Contributing page, unless there's a better more apparent place.

(Somewhat of a tangent, but to your point on #445, the Contributing guide is pretty overloaded with also being a quick start currently—it seems to me like a good step to split those two purposes, I may take a stab and see what you all think).

**Comment by woop** [comment]
> > Should we have a more evergreen way to refer to this? The Google Doc isn't version-specific so that's fine as-is, but perhaps we can link to it from primary documentation so people can easily be aware of it.
> 
> Sorry, I just noticed that it is linked on the README, but not on feast.dev GitBook I don't believe. Maybe it could be referenced on the Contributing page, unless there's a better more apparent place.
> 
> (Somewhat of a tangent, but to your point on #445, the Contributing guide is pretty overloaded with also being a quick start currently—it seems to me like a good step to split those two purposes, I may take a stab and see what you all think).

I get the same feeling. I think a development guide would be better. Let me first submit what I have and we can take it from there.

**Comment by woop** [comment]
> Should we have a more evergreen way to refer to this? The Google Doc isn't version-specific so that's fine as-is, but perhaps we can link to it from primary documentation so people can easily be aware of it.

I will also add it to feast.dev. Are you suggesting we move it to the repository itself maybe? A lot of projects just use markdown.

> Perhaps we could try to maintain [milestones in GitHub](https://github.com/gojek/feast/milestones)? I see their are some project boards set up for release versions already, it's surprising that GitHub doesn't seem to have obvious ways yet to integrate projects and milestones with automation.

To be honest, the GitHub projects API sucks. I havent found a way to scrape/automate it. Internally we are using Jira and its quite a pain to maintain both.

How would you want to split up work between milestones and projects? Do you want to map releases to milestones?
