### ISSUE TITLE
Feature Search/List/Browse

### ISSUE THREAD

**Issue by nfplay** [gojek/feast#435]
Is there a way to search for features? Or to browse/list them?

Thank you!

**Comment by woop** [comment]
Hi @nfplay!

Right now the primary way of listing/browsing is still at the [`feature set` ](https://api.docs.feast.dev/python/)level. We've redeveloped the Feast API from Feast 0.1 onwards, so some of the functionality has changed (feature browsing) and some has been temporarily deprioritized/deprecated (Feast UI).

We're trying to slowly stabilize the actual API and concepts, and as we do that we will introduce better search/discovery mechanisms. One of the primary ways we see Feast users do their discovery will be from entities that are registered in the system, and we have an issue tracking that work [here](https://github.com/gojek/feast/issues/405). The Feast UI is still on the cards as well, but it is a slightly lower priority at the moment compared to feature statistics and validation.
