### ISSUE TITLE
Max age should be optional

### ISSUE THREAD

**Issue by woop** [gojek/feast#440]
## Expected Behavior 

Setting `max_age` to 0 (or not configuring it) should allow users to look up data regardless of age.

## Current Behavior

During batch retrieval, no data is returned when `max_age` is set to 0.

## Steps to reproduce

1. Set `max_age` to 0 on a feature set
2. Retrieve features using `get_batch_features` with Python SDK.

## Possible Solution

Only need to add conditional logic to the SQL query that retrieves feature data.

**Comment by NicholaiStaalung** [comment]
+1 
Was about to raise a similar issue. This would solve it
