### ISSUE TITLE
FeatureSet.from_yaml and FeatureSet.from_dict resulting in blank feature sets

### ISSUE THREAD

**Issue by lgvital** [gojek/feast#452]
## Expected Behavior
```
>>> fs_dict = {'name': 'customer_transactions', 'kind': 'feature_set', 'entities': [{'name': 'customer_id', 'valueType': 'INT64'}], 'features': [{'name': 'daily_transactions', 'valueType': 'FLOAT'}, {'name': 'total_transactions', 'valueType': 'FLOAT', 'maxAge': '3600s'}]}`
>>> fs = FeatureSet.from_dict(fs_dict)
>>> fs.name
'customer_transactions'
```
## Current Behavior
```
>>> fs_dict = {'name': 'customer_transactions', 'kind': 'feature_set', 'entities': [{'name': 'customer_id', 'valueType': 'INT64'}], 'features': [{'name': 'daily_transactions', 'valueType': 'FLOAT'}, {'name': 'total_transactions', 'valueType': 'FLOAT', 'maxAge': '3600s'}]}`
>>> fs = FeatureSet.from_dict(fs_dict)
>>> fs.name
''
>>> fs.features
[]
```

The same thing happens with yaml and `from_yaml`.

## Steps to reproduce
```
from feast import FeatureSet
fs_dict = {'name': 'customer_transactions', 'kind': 'feature_set', 'entities': [{'name': 'customer_id', 'valueType': 'INT64'}], 'features': [{'name': 'daily_transactions', 'valueType': 'FLOAT'}, {'name': 'total_transactions', 'valueType': 'FLOAT', 'maxAge': '3600s'}]}`
fs = FeatureSet.from_dict(fs_dict)
```

### Specifications

- Version: 0.4.4
- Platform: OSX
- Subplatform: Python 3.7.6 (using local machine's CLI)

```
protobuf==3.11.2
```
## Possible Solution

```
        feature_set_proto = json_format.ParseDict(
            fs_dict, FeatureSetProto(), ignore_unknown_fields=True
        )
```

Seems related to this line since this ends up blank when run manually--perhaps a `protobuf` version issue, or something is off with `FeatureSetProto()`.

**Comment by woop** [comment]
Thanks for raising this @lgvital, will have a quick look!

**Comment by lgvital** [comment]
Thanks @woop, it's also possible I'm using the wrong expected dict/yaml?

**Comment by woop** [comment]
@lgvital I believe the problem is that you need to embed your specification into a `spec` key, for example:

```
fs_dict = {'spec': {'name': 'customer_transactions', 'kind': 'feature_set',
                    'entities': [{'name': 'customer_id', 'valueType': 'INT64'}],
                    'features': [
                        {'name': 'daily_transactions', 'valueType': 'FLOAT'},
                        {'name': 'total_transactions', 'valueType': 'FLOAT',
                         'maxAge': '3600s'}]}}
fs = FeatureSet.from_dict(fs_dict)
print(fs.name)
print(fs.features)
```

This is a change that was brought on by the new feature set specification, you can see the specification here: https://api.docs.feast.dev/grpc/feast.core.pb.html#FeatureSet

Basically we have two top level keys now: `spec`, and `meta`. All the existing keys have moved into `spec` and we have `createdTimestamp` and `status` within the `meta` object.

Let me know if that resolves the problem!

**Comment by lgvital** [comment]
That does work, thank you! Does an example in the docs somewhere or in a notebook make sense (if it doesn't already exist)?

**Comment by woop** [comment]
Hi @lgvital I have created this issue to track the documentation and development of that functionality https://github.com/gojek/feast/issues/455
