### ISSUE TITLE
Remove feature set versions from Feast serving API

### ISSUE THREAD

**Issue by woop** [gojek/feast#462]
Feature set "versions" will be deprecated in future versions of Feast. These versions currently apply to both ingestion and retrieval of data.

This deprecation will be a breaking change. In order to reduce the impact of this change, we'd like to remove "versions" from the feature retrieval API. 

Functionally this means that users are not allowed to provide a version, and that Feast Serving will always use the latest version of a feature set.

**Comment by ches** [comment]
For reference, discussion of the larger scope is #386.

**Comment by woop** [comment]
Closing this in favour of #386
