### ISSUE TITLE
Online serving not returning results in basic example

### ISSUE THREAD

**Issue by woop** [gojek/feast#468]
## Expected Behavior 
When running the [basic example](https://github.com/gojek/feast/blob/master/examples/basic/basic.ipynb) using GKE or Docker Compose, sending a feature request to an online serving endpoint should result in values being returned. 

## Current Behavior
A successful response is returned, but it contains no values for any of the keys

## Steps to reproduce

- Follow the [GKE installation guide](https://docs.feast.dev/installing-feast/gke)
- Run the basic example to ingest data and then retrieve data

**Comment by woop** [comment]
This issue was raised by Casey Kent in the #Feast slack channel: https://kubeflow.slack.com/archives/CE0L8T267/p1581301411043800

This request
```
online_features = client.get_online_features(
    feature_refs=[
        f"daily_transactions",
        f"total_transactions",
    ],
    entity_rows=[
        GetOnlineFeaturesRequest.EntityRow(
            fields={
                "customer_id": Value(
                    int64_val=1001)
            }
        )
    ],
)
print(online_features)
```

returns this response
```
fields {
  key: "customer_id"
  value {
    int64_val: 1001
  }
}
fields {
  key: "customer_project/daily_transactions"
  value {
  }
}
fields {
  key: "customer_project/total_transactions"
  value {
  }
}
```

In Redis he sees 
```
127.0.0.1:6379> get "\x12(customer_project/customer_transactions:1\x1a\x12\n\x0bcustomer_id\x12\x03 \xea\a"
"\x12\x1f\n\x12daily_transactions\x12\t))U\xf7m\xadg\x16@\x12\x18\n\x12total_transactions\x12\x02 U\x12\x12\n\x0bcustomer_id\x12\x03 \xea\a\x1a\x06\b\x80\xa0\xe4\xf0\x052(customer_project/customer_transactions:1"
```

**Comment by woop** [comment]
More information from slack conversation with Casey Kent. Casey followed (https://docs.feast.dev/installing-feast/docker-compose)
```
- cloned master branch
- edited bq-store.yml to use correct bq info
- created .env with service account key env vars and bucket name in gcp
```

**Comment by kckent34** [comment]
@woop Thanks for posting this. I am now able to retrieve features with online serving. 

Looks like this was an error on my end. I did not have **FEAST_HOME_DIR** set before running:
`docker-compose up -d`

I had opened another tab and forgot about it. Sorry for the confusion.

When running the following from examples/basic.ipynb:
```
online_features = client.get_online_features(
    feature_refs=[
        f"daily_transactions",
        f"total_transactions",
    ],
    entity_rows=[
        GetOnlineFeaturesRequest.EntityRow(
            fields={
                "customer_id": Value(
                    int64_val=1001)    
            }
        )
    ]
);
print(online_features)
```

I am now getting the following result, which seems correct:
```
field_values {
  fields {
    key: "customer_id"
    value {
      int64_val: 1001
    }
  }
  fields {
    key: "customer_project/daily_transactions"
    value {
      double_val: 5.984943777327984
    }
  }
  fields {
    key: "customer_project/total_transactions"
    value {
      int64_val: 65
    }
  }
}
```

**Comment by woop** [comment]
> Now, when running the following cell from examples/basic.ipynb:

That's interesting. Did anything change between your runs?

**Comment by kckent34** [comment]
Well at first, after bringing everything down, i brought it back up with  FEAST_HOME env variable set, and it worked. Then i looked and there was nothing in dockerfile that was using it so i removed it, and it still worked.

**Comment by woop** [comment]
> @woop
> Well at first, after bringing everything down, i brought it back up with FEAST_HOME env variable set, and it worked. Then i looked and there was nothing in dockerfile that was using it so i removed it, and it still worked.

Ok, thanks @kckent34. Can we resolve this issue for now?

**Comment by kckent34** [comment]
@woop yes

**Comment by liorshk** [comment]
Hi, I got the same error(empty results for online serving). Working on Windows.
I tried to restart but nothing changed.

**Comment by woop** [comment]
> Hi, I got the same error(empty results for online serving). Working on Windows.
> I tried to restart but nothing changed.

@liorshk are you using Docker Compose? Are you running the Python SDK from the Jupyter environment provided by Compose? Does batch serving work?

**Comment by liorshk** [comment]
@woop I am using docker compose and I didn't install batch serving (I am without GCP).
I am running basic.ipynb from the jupyter environment.

**Comment by imjuanleonard** [comment]
Hi, @liorshk are you still facing the issue?

I have tested both the online serving from `docker-compose` and from GKE setup, both are working fine following the tutorials although I am using OSX 10.15.3 and tested on Ubuntu.

Can you provide more details on the [Feast Slack Channel(https://kubeflow.slack.com/join/shared_invite/enQtNDg5MTM4NTQyNjczLTdkNTVhMjg1ZTExOWI0N2QyYTQ2MTIzNTJjMWRiOTFjOGRlZWEzODc1NzMwNTMwM2EzNjY1MTFhODczNjk4MTk)

As I believe it is more of a debugging issue, here are the details required:
-> Windows version
-> Which docker app and  version
-> Which VirtualMachine app and version

Will wait for your reply, otherwise will close this thread

Thanks
