### ISSUE TITLE
Redis High Availability

### ISSUE THREAD

**Issue by woop** [gojek/feast#478]
**Is your feature request related to a problem? Please describe.**

Currently we do not natively support Redis in high availability mode for online serving. 
- Redis is a single point of failure
- Redis cannot currently scale out more than one node, leading to resource utilization problems (disk, cpu).

Additionally, there is a problem with the current implementation of the Redis client in Apache Beam where it establishes too many connections to Redis.

**Describe the solution you'd like**
The goal is to add support for HA Redis as part of Feast. This would require
1. Users should be able to configure the addresses to these stores as part of their serving deployment. This may necessitate an update the Redis store in the [store.proto](https://github.com/gojek/feast/blob/master/protos/feast/core/Store.proto) (or the creation of a new type of store like `RedisCluster`.
2. Refactoring the [Feast Redis IO](https://github.com/gojek/feast/blob/master/ingestion/src/main/java/feast/store/serving/redis/RedisCustomIO.java#L302) in the Apache Beam ingestion code to support Redis clusters.
3. Refactoring the [Feast Serving client](https://github.com/gojek/feast/blob/master/serving/src/main/java/feast/serving/service/RedisServingService.java) to support Redis clusters.
4. Ensuring that the Redis clients (both for cluster and non-cluster mode) do not create an excessive amount of connections. Ideally each dataflow or beam node should be sharing a single connection pool between all bundles.
5. EDIT: We should try to use [Lettuce](https://github.com/lettuce-io/lettuce-core) as the Redis Client for both serving and ingestion. 
https://github.com/spring-projects/spring-session/issues/789
https://github.com/lettuce-io/lettuce-core

**Comment by Yanson** [comment]
I would take this opportunity to close #247 and switch to:
https://github.com/lettuce-io/lettuce-core

**Comment by woop** [comment]
> I would take this opportunity to close #247 and switch to:
> https://github.com/lettuce-io/lettuce-core

Hell yea. Adding this to the solution above.
