### ISSUE TITLE
Python SDK

### ISSUE THREAD

**Issue by woop** [gojek/feast#48]
Creating an issue to track the addition of a Python SDK for Feast:

* RFC: [Python SDK](https://github.com/gojek/feast/blob/master/rfcs/0001-python-sdk.md)
* PR: #47

**Comment by tims** [comment]
Further feedback:

The main thing that I think we'll need to think more about, is how the notion of a dataset will work in an environment without BigQuery. One way to do this, would be rather saving query results back to BQ tables, we could read them from the warehouse is in beam and export them again using beam. Then the warehouse wouldn't have to be BQ. Eg, exporting them as Avro files would be pretty neat.

**Comment by woop** [comment]
> Further feedback:
> 
> The main thing that I think we'll need to think more about, is how the notion of a dataset will work in an environment without BigQuery. One way to do this, would be rather saving query results back to BQ tables, we could read them from the warehouse is in beam and export them again using beam. Then the warehouse wouldn't have to be BQ. Eg, exporting them as Avro files would be pretty neat.

Is there anything that couples us to BQ right now? The way I see it is we will have a feature warehouse where we will create these datasets (that will remain the source of truth). When the user wants to retrieve it, the dataset table is exported in file format to some staging location, and then the user can download it through through our client. That process can happen in any way, Beam or otherwise. 

We should definitely support structured data as the default, with my preference being Parquet. Avro is also a strong contender.

**Comment by tims** [comment]
There is, in that there isn't a way to create training datasets from the warehouse if the warehouse is just files (currently our only other supported warehouse sink). Which suggests flat files aren't suitable warehouse sinks.

I think we can close this now that the SDK is merged in. Alternative open source warehouse stores are a future issue.
