### ISSUE TITLE
Getting Core gRPC error from server Core: 6565 in Basic Example

### ISSUE THREAD

**Issue by tomthebuzz** [gojek/feast#484]
## Expected Behavior 

As described in Basic Example Notebook

## Current Behavior

Create a project workspace
In [10]: client.create_project('customer_project')

**Jupyter Cell Response**
`
FutureTimeoutError                        Traceback (most recent call last)
/opt/conda/lib/python3.7/site-packages/feast/client.py in _connect_core(self, skip_if_connected)
    191             grpc.channel_ready_future(self.__core_channel).result(
--> 192                 timeout=GRPC_CONNECTION_TIMEOUT_DEFAULT
    193             )

/opt/conda/lib/python3.7/site-packages/grpc/_utilities.py in result(self, timeout)
    139     def result(self, timeout=None):
--> 140         self._block(timeout)
    141 

/opt/conda/lib/python3.7/site-packages/grpc/_utilities.py in _block(self, timeout)
     85                         if remaining < 0:
---> 86                             raise grpc.FutureTimeoutError()
     87                         else:

FutureTimeoutError: 

During handling of the above exception, another exception occurred:

ConnectionError                           Traceback (most recent call last)
<ipython-input-10-5285c61094b4> in <module>
----> 1 client.create_project('customer_project')

/opt/conda/lib/python3.7/site-packages/feast/client.py in create_project(self, project)
    274         """
    275 
--> 276         self._connect_core()
    277         self._core_service_stub.CreateProject(
    278             CreateProjectRequest(name=project), timeout=GRPC_CONNECTION_TIMEOUT_DEFAULT

/opt/conda/lib/python3.7/site-packages/feast/client.py in _connect_core(self, skip_if_connected)
    194         except grpc.FutureTimeoutError:
    195             raise ConnectionError(
--> 196                 f"Connection timed out while attempting to connect to Feast "
    197                 f"Core gRPC server {self.core_url} "
    198             )

ConnectionError: Connection timed out while attempting to connect to Feast Core gRPC server core:6565 

`

### Specifications

- Version: Latest / Cloned and followed local install / setup instructions
- Platform: OS X
- Subsystem: Miniconda activated ENV

Tried both Chrome and Safari as Jupyter browser.
All the previoussteps (incl. the PIP install / upgrade completed without error

**Comment by woop** [comment]
Hi @tomthebuzz!

Thanks for trying out the software.

The above error does come up when trying to connect to a deployment of Feast that isn't live yet. Generally it takes around 30-60 seconds to start the system up the first time. Not sure if that is perhaps the problem

Are you running on GKE or using Docker Compose?

**Comment by tomthebuzz** [comment]
Thanks for checking back. Am running on docker-compose and by now have re-installed everything multiple times and also made sure (via grpc_cli) that the base grpc install works. I repeatedly get the following error when feast core is trying to create the jdbc metadata connection:

```
core_1            | 2020-02-22 18:28:00.793  WARN dfffde7afadc --- [           main] o.h.e.j.e.i.JdbcEnvironmentInitiator     : HHH000342: Could not obtain connection to query metadata : The connection attempt failed.
core_1            | 2020-02-22 18:28:00.810  WARN dfffde7afadc --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]
core_1            | 2020-02-22 18:28:00.893  INFO dfffde7afadc --- [           main] o.a.c.c.StandardService                  : Stopping service [Tomcat]
feast_core_1 exited with code 1
```

**Comment by woop** [comment]
Hi @tomthebuzz. Two quick questions
1. Have you modified any configuration, or are you using the default Docker Compose configuration?
2. Are you running the SDK from the Docker Compose notebook, or from your local machine?

I just did the following
```
git clone https://github.com/gojek/feast
cd feast/infra/docker-compose
cp .env.sample .env
docker-compose up -d
```
which brings everything up besides batch serving (which is expected because I havent configured it)

It could be that there is a connectivity problem to your database. Is your database coming online?

**Comment by liorshk** [comment]
Had the same error. The reason for me was that POSTGRES was down.
 Solved it by adding POSTGRES password to docker-compose:
```yaml  
db:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5342"
```
and adding the password to the environment file `.env`
