### ISSUE TITLE
Remove auto generated files from git

### ISSUE THREAD

**Issue by pmjacinto** [gojek/feast#494]
## Expected Behavior 

After fixing #448 remove the auto generated files from git.

https://github.com/gojek/feast/tree/master/sdk/go/protos/feast
"pb2" files in https://github.com/gojek/feast/tree/master/sdk/python/feast 

## Current Behavior

Proto gen files in the Python / Go sdk commited to the repo.

## Steps to reproduce

N/A

### Specifications

latest master

## Possible Solution

delete the files, add .gitignore rules, make sure CI still works

**Comment by woop** [comment]
This is resolved for Python, which seems to be the main pain point.
