### ISSUE TITLE
Clean up Feast configuration

### ISSUE THREAD

**Issue by woop** [gojek/feast#525]
Creating this card to clean up the Feast Core and Feast Serving configuration files. The configuration files have the following problems
- No clear separation of static Spring or JVM configuration from user level configuration
- Duplicate configuration points for the same thing (BigQuery, or Dataflow configuration)
- Lack of documentation of the options that are configurable.
- Lack of documentation on where new configuration should be placed.
- [EDIT] Adding more scope to this refactor. Configuration should also be easy to define and pass to stores. Validation should happen at the storage layer, not in Feast Core or Feast Serving. This change should make it easier to support stores as interfaces, possibly with factories building the stores/retrievers based on configuration. 

This issue tracks the refactor, cleanup, and documentation to solve the above.

**Comment by mrzzy** [comment]
Not sure if this should be a separate issue, but this is definitely a pain point. There is almost no documentation on [feast.dev](feast.dev) the configuring and using Dataflow runner except that it is faster and more reliable than DirectRunner. Had to reverse engineer the config file from `core/src/main/java/feast/core/config/JobConfig.java`

**Comment by woop** [comment]
Yea, that is definitely a major pain point. Thanks for pointing it out and being so detailed.

**Comment by woop** [comment]
Throwing this into the ring as well. The following BQ configuration parameters must be set for BQ retrieval to work.
```
bigquery-initial-retry-delay-secs: 
bigquery-total-timeout-secs: 21600
```

**Comment by woop** [comment]
Two more notes. 
- We can generate configuration metadata from @ConfigurationProperties annotated classes (like FeastProperties). This produces a JSON with keys/descriptions/defaults for all `feast` keys in `application.yml`. We could easily convert that into markdown and publish it to docs.feast.dev. I
- We should ensure that our JavaDocs are up to date. It's currently not being generated.

**Comment by ches** [comment]
> * We can generate configuration metadata from @ConfigurationProperties annotated classes (like FeastProperties)

The account which someone apparently created to catch accidental mentions like that one is my favorite thing on the Internet today.

Returning to my seat in the peanut gallery now.

**Comment by woop** [comment]
> > * We can generate configuration metadata from @ConfigurationProperties annotated classes (like FeastProperties)
> 
> The account which someone apparently created to catch accidental mentions like that one is my favorite thing on the Internet today.
> 
> Returning to my seat in the peanut gallery now.

Just noticed it, hahahahahahha

**Comment by woop** [comment]
Keeping this open for the time being until #458 is done.

**Comment by woop** [comment]
I believe this issue is done enough. Let's open a new one if needed.
