### ISSUE TITLE
Add build process for docker images

### ISSUE THREAD

**Issue by zhilingc** [gojek/feast#55]
To begin with, we can just push the docker images to a public gcr repository. Later we can see about migrating it to Dockerhub.

Will use google cloud build for this.

**Comment by tims** [comment]
Sorry, I should have asked this earlier.. 

Why are we not using the maven docker plugin to build the docker images anymore? If we were using that we could push to gcr directly using `mvn deploy`.

**Comment by zhilingc** [comment]
> Sorry, I should have asked this earlier..
> 
> Why are we not using the maven docker plugin to build the docker images anymore? If we were using that we could push to gcr directly using `mvn deploy`.

We needed to build ingestion first then bake both ingestion and core jars (which are in separate directories) into the core docker image. There wasn't a way to do it with the maven docker plugin.

**Comment by tims** [comment]
closing this as it's fine for now.
