### ISSUE TITLE
Chore: Add badge

### ISSUE THREAD

**Issue by imjuanleonard** [gojek/feast#563]
Think it would be great when we have GitHub coverage badge, build badge, etc

**Comment by woop** [comment]
Good idea, this would be easy to do now that we have unit tests and builds in GitHub Actions.

![](https://github.com/gojek/feast/workflows/unit%20tests/badge.svg)

**Comment by ches** [comment]
When GitHub suggest badge markup them in the Actions UI, they don't include a link to anything useful so far… linking to the latest workflow run for viewed branched would be good I think [but that doesn't seem easily possible yet][1].

In lieu of that, perhaps linking to the list of runs is the best we can do.

- https://github.com/gojek/feast/actions?query=workflow%3A%22unit+tests%22
- https://github.com/gojek/feast/actions?query=workflow%3Alinting

[1]: https://github.community/t5/GitHub-Actions/Linking-to-runs/td-p/44140

**Comment by woop** [comment]
> When GitHub suggests badge markup for them in the Actions UI, they don't include a link to anything useful so far… linking to the latest workflow run for viewed branch would be good I think [but that doesn't seem easily possible yet](https://github.community/t5/GitHub-Actions/Linking-to-runs/td-p/44140).
> 
> In lieu of that, perhaps linking to the list of runs is the best we can do.
> 
> * https://github.com/gojek/feast/actions?query=workflow%3A%22unit+tests%22
> * https://github.com/gojek/feast/actions?query=workflow%3Alinting

Happy with the latter. Will submit a PR.

**Comment by woop** [comment]
On second thought, just have a look at the badges above. I have updated them. They now look at the master branch only (which should be the only one we care about).

If you are happy then I will commit them.

Side note: Guess we should rename it from `linting` to `lint` or `lint`? All sounds weird to me.

**Comment by ches** [comment]
> Side note: Guess we should rename it from `linting` to `lint` or `linter`? Hmmm, everything sounds weird to me.

"Code quality" or "code standards" maybe? The latter always sounds a bit stuffy to me but is pretty common parlance and is what a section of contributing guide is currently titled.

**Comment by woop** [comment]
> > Side note: Guess we should rename it from `linting` to `lint` or `linter`? Hmmm, everything sounds weird to me.
> 
> "Code quality" or "code standards" maybe? The latter always sounds a bit stuffy to me but is pretty common parlance and is what a section of contributing guide is currently titled.

Sure, let's run with `code standards`

**Comment by woop** [comment]
Ok, I've fired the laser. Please feel free to propose new tweaks.
