### ISSUE TITLE
Allow for disabling of metrics pushing

### ISSUE THREAD

**Issue by zhilingc** [gojek/feast#57]
**Is your feature request related to a problem? Please describe.**
Without a valid statsd endpoint, the entire deployment will fail. While useful, we shouldn't make it mandatory for users to deploy the tick stack together with Feast. Core still maintains the latest metrics retrieved even in the absence of a separate db. 

**Describe the solution you'd like**
Allow for users to toggle metrics pushing to an external db on/off.

**Comment by tims** [comment]
Are we setting the --metricsSink parameter in beam? or is this totally internal to core?

**Comment by woop** [comment]
@zhilingc Is this still relevant?

**Comment by woop** [comment]
Closing since this has been resolved.
