### ISSUE TITLE
Feast slack link is invalid 

### ISSUE THREAD

**Issue by Jeffwan** [gojek/feast#571]
## Expected Behavior 

I can join Feast slack channel by clicking
https://github.com/gojek/feast#important-resources 

## Current Behavior
This invite link is no longer active.

## Steps to reproduce
Just Click it

### Specifications

- Version:
- Platform:
- Subsystem:

## Possible Solution

Could you add a new link or invite me to the channel? My email is seedjeffwan((at)) gmail

**Comment by ches** [comment]
Yeah these expire from time to time and Kubeflow folks have to generate a fresh link… [the Kubeflow Community page](https://www.kubeflow.org/docs/about/community/#slack-community-and-channels) is likely to be freshened first, it's a little annoying but maybe the Feast README should link to there to avoid this staleness.

@Jeffwan it looks like they have a valid link there already, if you haven't gotten in yet.

**Comment by Jeffwan** [comment]
@ches Is feast sharing the slack team with Kubeflow? So feast has it own channel right?

**Comment by ches** [comment]
Yep, exactly.

**Comment by woop** [comment]
Thanks @Jeffwan 

Should be fixed now :blush:

**Comment by woop** [comment]
The new link is permanent: https://github.com/kubeflow/website/issues/1793#issuecomment-598841529

**Comment by Jeffwan** [comment]
> The new link is permanent: [kubeflow/website#1793 (comment)](https://github.com/kubeflow/website/issues/1793#issuecomment-598841529)

Thanks! Good to know. I thought it's a different namespace, I am actually already there. I will join feast channel.
