### ISSUE TITLE
Basic example fails when importing Pandas

### ISSUE THREAD

**Issue by benmackenzie-exos** [gojek/feast#585]
following:

git clone https://github.com/gojek/feast.git
cd feast/infra/docker-compose
cp .env.sample .env
docker-compose up -d

and then:

http://localhost:8888/notebooks/feast/examples/basic/basic.ipynb

executing one cell at a time.  everything works up to the 'import necessary modules' cell.  

ImportError: cannot import name 'check_array_indexer' from 'pandas.core.indexers' (/opt/conda/lib/python3.7/site-packages/pandas/core/indexers.py)

**Comment by woop** [comment]
Hi @benmackenzie-exos!

Quick question, did you use from PyPi or did you use your local Feast repository to install the client?

**Comment by woop** [comment]
@benmackenzie-exos Can you also please run `pip freeze` and provide us with the results? I think there might be an API change in the latest version of Pandas.

**Comment by BenMacKenzie** [comment]
PyPi...


I'll do that...I shut everything down, so I need to restart all of the docker images and follow example again...later today..

**Comment by BenMacKenzie** [comment]
pip freeze:

alembic==1.4.1
async-generator==1.10
attrs==19.3.0
backcall==0.1.0
beautifulsoup4==4.8.2
bleach==3.1.3
blinker==1.4
bokeh==1.4.0
cachetools==4.0.0
certifi==2019.11.28
certipy==0.1.3
cffi==1.14.0
chardet==3.0.4
click==7.1.1
cloudpickle==1.3.0
conda==4.8.2
conda-package-handling==1.6.0
confluent-kafka==1.3.0
cryptography==2.8
cycler==0.10.0
Cython==0.29.15
cytoolz==0.10.1
dask==2.11.0
decorator==4.4.2
defusedxml==0.6.0
dill==0.3.1.1
distributed==2.12.0
entrypoints==0.3
fastavro==0.22.13
feast==0.4.7
fsspec==0.6.2
google==2.0.3
google-api-core==1.14.3
google-auth==1.6.3
google-cloud-bigquery==1.18.1
google-cloud-bigquery-storage==0.7.0
google-cloud-core==1.0.3
google-cloud-storage==1.20.0
google-resumable-media==0.4.1
googleapis-common-protos==1.51.0
grpcio==1.27.2
h5py==2.10.0
HeapDict==1.0.1
idna==2.9
imageio==2.8.0
importlib-metadata==1.5.0
ipykernel==5.1.4
ipympl==0.5.3
ipython==7.13.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
jedi==0.16.0
Jinja2==2.11.1
joblib==0.14.1
json5==0.9.0
jsonschema==3.2.0
jupyter-client==6.0.0
jupyter-core==4.6.3
jupyter-telemetry==0.0.5
jupyterhub==1.1.0
jupyterlab==2.0.1
jupyterlab-server==1.0.7
kafka-python==1.4.7
kiwisolver==1.1.0
llvmlite==0.31.0
locket==0.2.0
Mako==1.1.0
MarkupSafe==1.1.1
matplotlib==3.1.3
mistune==0.8.4
mpmath==1.1.0
msgpack==1.0.0
nbconvert==5.6.1
nbformat==5.0.4
networkx==2.4
notebook==6.0.3
numba==0.48.0
numexpr==2.7.1
numpy==1.18.2
oauthlib==3.0.1
olefile==0.46
packaging==20.1
pamela==1.0.0
pandas==1.0.2
pandavro==1.5.1
pandocfilters==1.4.2
parso==0.6.2
partd==1.1.0
patsy==0.5.1
pexpect==4.8.0
pickleshare==0.7.5
Pillow==7.0.0
prometheus-client==0.7.1
prompt-toolkit==3.0.4
protobuf==3.11.4
psutil==5.7.0
ptyprocess==0.6.0
pyarrow==0.16.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycosat==0.6.3
pycparser==2.20
pycurl==7.43.0.5
Pygments==2.6.1
PyJWT==1.7.1
pyOpenSSL==19.1.0
pyparsing==2.4.6
pyrsistent==0.15.7
PySocks==1.7.1
python-dateutil==2.8.1
python-editor==1.0.4
python-json-logger==0.1.11
pytz==2019.3
PyWavelets==1.1.1
PyYAML==5.3
pyzmq==19.0.0
requests==2.23.0
rpy2==3.1.0
rsa==4.0
ruamel-yaml==0.15.80
ruamel.yaml.clib==0.2.0
scikit-image==0.16.2
scikit-learn==0.22.2.post1
scipy==1.4.1
seaborn==0.10.0
Send2Trash==1.5.0
simplegeneric==0.8.1
six==1.14.0
sortedcontainers==2.1.0
soupsieve==2.0
SQLAlchemy==1.3.15
statsmodels==0.11.1
sympy==1.5.1
tabulate==0.8.7
tblib==1.6.0
terminado==0.8.3
testpath==0.4.4
toml==0.10.0
toolz==0.10.0
tornado==6.0.4
tqdm==4.44.1
traitlets==4.3.3
tzlocal==2.0.0
urllib3==1.25.8
vincent==0.4.4
wcwidth==0.1.8
webencodings==0.5.1
widgetsnbextension==3.5.1
xlrd==1.2.0
zict==2.0.0
zipp==3.1.0

**Comment by HaebinShin** [comment]
@BenMacKenzie 
I got the same issue.
It seems that the pandas version is something wrong.
In [setup.py](https://github.com/gojek/feast/blob/master/sdk/python/setup.py#L36), feast requires pandas=='0.'.
When I reinstall pandas==0.25.3, the problem was solved.

**Comment by BenMacKenzie** [comment]
any reason why feast_jupyter_1 couldn't come with all packages installed?

**Comment by BenMacKenzie** [comment]
but that did seem to help...

**Comment by HaebinShin** [comment]
Hmm... I don't know why the pip install pandas==1.0.2.
I tried to check if any other packages require pandas==1.* , but it seems no problem...

<img width="554" alt="스크린샷 2020-04-01 오전 12 32 01" src="https://user-images.githubusercontent.com/6428529/78045622-27103280-73b1-11ea-802f-4c9fcfc6bc2e.png">

**Comment by woop** [comment]
Hey @benmackenzie-exos and @HaebinShin, thanks for helping out here.

We had a prebaked Jupyter image previously. I think it makes sense, but I wanted to ensure that we have less inconsistencies between these docker images and the actual code, which is why we want folks to install the client and download dependencies. I think the root problem here is the combination of dependencies are incompatible, so I think we should be looking at that first. 

@imjuanleonard has been assigned to see if he can resolve this.

**Comment by imjuanleonard** [comment]
Hi @BenMacKenzie @HaebinShin,
Thanks for reporting the issue, 

The issue was, The `jupyter/data-science:latest` notebook image that we use in docker-compose was prebaked with pandas library.

Just two weeks ago, they updated their latest tag to use `pandas 1.0.2` thus causing the failing import because the prebaked pip have already bumped version than our feast specified. 

Hence have raised the #597, to resolve this issue, for now.
cc: @woop
