### ISSUE TITLE
Fix version on master branch

### ISSUE THREAD

**Issue by woop** [gojek/feast#589]
## Expected Behavior 
The master branch version should be pointed at `0.5-SNAPSHOT`

## Current Behavior
The master branch version is set as `0.4.2-SNAPSHOT`

https://github.com/gojek/feast/blob/master/pom.xml#L39

## Possible Solution

- Short term: Just update it. Also update any other version occurrences in code
- Long term: Consider updating the `code standards` workflow to prevent old versions from being reused on the master branch.

**Comment by ches** [comment]
Also relates to #476

**Comment by woop** [comment]
I believe this is done.
