### ISSUE TITLE
Batch Ingestion to BQ fails with permission issues

### ISSUE THREAD

**Issue by NicholaiStaalung** [gojek/feast#591]
## Expected Behavior 
Ingesting features to bigquery via feast with client.ingest() from the python sdk

## Current Behavior
The ingestion hangs and eventually (After several minutes) throws a kafka error.

![image](https://user-images.githubusercontent.com/25878853/77895394-ff1cb400-7276-11ea-970c-b5ec04269ebd.png)

When inspecting the feast core logs it throws a permission error for the feast dataset

> User does not have bigquery.datasets.get permission for dataset datascienceplatform-266011:feast

The feast service account had project editor rights and i checked with bigquery dataset permissions and the editor rights were correctly inherited. However, i changed to owner rights without any success.

I have attached the feast core logs here.
[feast-feast-feast-core-59f659c4cb-ktkrq-1585555960760032000.log](https://github.com/gojek/feast/files/4401736/feast-feast-feast-core-59f659c4cb-ktkrq-1585555960760032000.log)

## Steps to reproduce
I have reproduced it with the basic example. However, we are using feast from inside kubeflow on GKE (same cluster) with only internal ip access to the GKE pods. I checked [#427 ] but those configurations were applied and we didnt find any inconsistencies.

Im capable of connecting to feast and create projects and feature sets without issues.

### Specifications

- Version: feast 0.4.7
- Platform: GKE 
- Subsystem: Kubeflow 1.0

## Possible Solution
Something inside GKE is not handling permissions correctly and im not sure if this is even a feast issue, but at least feast is not handling the errors well as there are no obvious relation between error messages being thrown in my notebook and the pod logs.

Help is greatly appreciated!

**Comment by woop** [comment]
@NicholaiStaalung did you manually create the dataset or did Feast create it? Normally Feast should automatically create it when you first apply a Feature Set. That would ensure that it has the right permissions.

You can also try to add the email of the Feast service account to have the correct BQ dataset permissions. This is possible through the BQ UI itself.

> but at least feast is not handling the errors well as there are no obvious relation between error messages being thrown in my notebook and the pod logs.

This is a pain. Also experienced it. I've documented similar pains here: https://github.com/gojek/feast/issues/584

**Comment by NicholaiStaalung** [comment]
@woop 
I created the feature set via feast with client.apply()

First i created a project 
`client.create_project('testtest')`

The i set that project 
`client.set_project('testtest')`

then i initiated the feature set
`indbetaling_fs = FeatureSet(
    "testtesttest",
    entities=[Entity(name='Id', dtype=ValueType.STRING)],
    max_age=Duration(seconds=432000)    
)`

And then i did 
`indbetaling_fs.infer_fields_from_df(df, replace_existing_features=True)`

And then i called `client.apply('testtesttest, df)`


I checked the BQ UI and the service account had owner permission. I actually added the service account to all permissions just in case without any luck

**Comment by NicholaiStaalung** [comment]
I just noticed that tables in BQ is actually created but not populated with data. And we moved past the error by reinstalling feast in the cluster. However there is no data being populated according to the statistics and no data in BQ. We are not seeing any error in the logs
![image](https://user-images.githubusercontent.com/25878853/77919873-030ffc80-729e-11ea-8ded-a9681e5e1e18.png)

**Comment by NicholaiStaalung** [comment]
We got around it by exposing the external IP via nodeport. Closing.

Since we are not using feast from outside the cluster it would be nice to add a config for feast that doesn't rely on nodeport so we dont have to expose endpoints. Maybe you can add it to the roadmap?
