### ISSUE TITLE
Remove Force Update from Python SDK ingest.py

### ISSUE THREAD

**Issue by imjuanleonard** [gojek/feast#598]
## Background
The Python SDK has a method called force update in the ingest method, where it will first apply the feature set from the first row of the PyArrow first

The methods are:
https://github.com/gojek/feast/blob/master/sdk/python/feast/client.py#L651

As suggested by @woop #593 

`We can probably safely remove force_update here. It's better if people run that as a separate step. Not sure if anyone is using it right now internally, and I think as written it was partly broken anyways.`

## Possible Solution
- Check with the user internally, and deprecate the function

**Comment by woop** [comment]
@imjuanleonard I'd recommend adding links to the methods in question
