### ISSUE TITLE
Add support for ingesting from BigQuery SQL statement / View

### ISSUE THREAD

**Issue by pradithya** [gojek/feast#6]
Currently Feast only support ingesting feature from BigQuery Table.

**Comment by woop** [comment]
This issue isn't clearly described. Feast supports ingesting features from BigQuery, CSVs, as well as streams.

**Comment by pradithya** [comment]
My bad. Yes, feast supports ingesting features from all those sources, although currently for BigQuery case it is still limited to consuming a `table`. Adding supports to ingest from BQ view or SQL query could add more flexibility of data source.

**Comment by bethrice44** [comment]
Any updates on this? It would be really useful to be able to ingest views

**Comment by woop** [comment]
> Any updates on this? It would be really useful to be able to ingest views

Hi Beth,

We are currently making some significant breaking changes to Feast, after which we expect to be able to ingest BQ views.

**Comment by woop** [comment]
Closing this issue for now. It is based on Feast 0.1. We will be revisiting this with enhancements to the feature set specification.
