### ISSUE TITLE
basic example doesn't return data

### ISSUE THREAD

**Issue by BenMacKenzie** [gojek/feast#600]
just following the basic example in jupyter.

## Current Behavior
online_features = client.get_online_features(
    feature_refs=[
        f"daily_transactions",
        f"total_transactions",
    ],
    entity_rows=[
        GetOnlineFeaturesRequest.EntityRow(
            fields={
                "customer_id": Value(
                    int64_val=1001)
            })
       
    ],
)
print(online_features)

produces:

field_values {
  fields {
    key: "customer_id"
    value {
      int64_val: 1001
    }
  }
  fields {
    key: "customer_project2/daily_transactions"
    value {
    }
  }
  fields {
    key: "customer_project2/total_transactions"
    value {
    }
  }
}

note that there does appear to be data in the kafka features topic.  I'm not sure if that is where the online feature service is getting the data or whether it is in redis.

**Comment by imjuanleonard** [comment]
Hello @BenMacKenzie 
Last time some other people find the same issue, but I cannot replicate it yet.
May I know your Platform specification?
```
OS
Docker Version
```
Thanks



> note that there does appear to be data in the Kafka features topic. I'm not sure if that is where the online feature service is getting the data or whether it is in Redis.

Normally the data will be pushed to Kafka, and the Ingestion Job is going to Ingest the Data from Kafka to Redis

**Comment by woop** [comment]
@BenMacKenzie Have you made any changes to the `max_age`?

**Comment by BenMacKenzie** [comment]
I just re-did everything and it works fine.  Maybe while struggling with the pandas issue more than 432000 seconds elapsed (5 days)? 

thanks!
