### ISSUE TITLE
No exception when connecting to Kafka fails

### ISSUE THREAD

**Issue by avolution** [gojek/feast#626]
Hey guys,

I have installed feast(0.4.4) via Helm3 on GKE 

The Basic example is working until the ingestion (online serving) part

There I get ->>

Waiting for feature set to be ready for ingestion...
  0%|          | 0/15 [00:00<?, ?rows/s]

but there is no progress.

When I look on GCPs bigquery interface I can see that the project "customer_project" is created with the correct columns in "customer_transactions".
But for sure no data

get_feature_set gives me 

{
  "spec": {
    "name": "customer_transactions",
    "version": 1,
    "entities": [
      {
        "name": "customer_id",
        "valueType": "INT64"
      }
    ],
    "features": [
      {
        "name": "daily_transactions",
        "valueType": "DOUBLE"
      },
      {
        "name": "total_transactions",
        "valueType": "INT64"
      }
    ],
    "maxAge": "432000s",
    "source": {
      "type": "KAFKA",
      "kafkaSourceConfig": {
        "bootstrapServers": "feast-kafka:9092",
        "topic": "feast"
      }
    },
    "project": "customer_project_1"
  },
  "meta": {
    "createdTimestamp": "2020-04-15T10:26:51Z",
    "status": "STATUS_READY"
  }
}

I had to modify some port service setup in the chart so it can be that some of feast have connection issues between kafka etc.
But There are no errors in the logs of the core and serving pod.

What can be the problem and how is a way to debug that?

**Comment by woop** [comment]
Hi @avolution, thank you for trying out Feast!

> Waiting for feature set to be ready for ingestion...

This normally means you have just applied a feature set and Feats is busy setting up a job to ingest data. Ingestion jobs are long running, which in turn allows them to be more responsive.

Did the ingestion eventually start?

If it didn't start, can you confirm that you are able to connect to `feast-kafka` from the environment in which you are running the SDK? Your brokers are `feast-kafka:9092` which means you should be able to connect to that Kafka broker. A simple netcat/telnet should confirm whether your connectivity is up.

**Comment by avolution** [comment]
> If it didn't start, can you confirm that you are able to connect to `feast-kafka` from the environment in which you are running the SDK? Your brokers are `feast-kafka:9092` which means you should be able to connect to that Kafka broker. A simple netcat/telnet should confirm whether your connectivity is up.

That was exactly the Problem.
I was not aware that the SDK needs access to kafka (thought the data is transmited via the core service)

Executed inside the cluster with access to kafka it's working fine!
Thank you! :)

**Comment by woop** [comment]
Thanks for getting back to us @avolution! Glad it worked out

I am going to co-opt this issue and change it into a card for one of our engineers to pick up.

We need to make sure that the correct exception is thrown if connectivity to Kafka is not up.
