### ISSUE TITLE
Get ingestion metrics when running on Flink runner

### ISSUE THREAD

**Issue by pradithya** [gojek/feast#63]
**Is your feature request related to a problem? Please describe.**
Currently pulling metrics from Flink Runner is not implemented yet. 

**Describe the solution you'd like**
Use [Flink REST API](https://ci.apache.org/projects/flink/flink-docs-release-1.5/monitoring/rest_api.html) to pull metrics from

**Comment by woop** [comment]
This issue isn't relevant any more due to changes in Feast 0.3.0.
