### ISSUE TITLE
Helm chart for deploying feast using Flink as runner

### ISSUE THREAD

**Issue by pradithya** [gojek/feast#64]
**Describe the solution you'd like**
Update helm chart to support deploying Feast with Flink runner

**Comment by tims** [comment]
Would this actually deploy a flink instance on kubernetes?

**Comment by tims** [comment]
I think this, and redis should be separate helm charts

**Comment by woop** [comment]
> I think this, and redis should be separate helm charts

I think it makes sense to allow these components to be deployed with the Helm chart, but make them optional. That way we can make quickstarting easier, but don't force users to use these components.

**Comment by woop** [comment]
This issue isn't relevant any more due to changes in Feast 0.3.0. We might not have to run Flink at all.
