### ISSUE TITLE
Create a release

### ISSUE THREAD

**Issue by woop** [gojek/feast#65]
I think it's important that we separate any new development from bug fixes. We should have a release out of Feast that is stable and can be used in production.

If we want to develop new breaking changes then that should be prioritized for a future release, and development should maybe continue on a separate branch.

@tims @pradithya @zhilingc

**Comment by tims** [comment]
We discussed this in the community call I think, that we should make our first release 0.1.0. So we need to reset the version numbers in the pom and such.

**Comment by tims** [comment]
Let's discuss the strategy for making the release at next week's community call. 

*I believe at this stage, we then just need to manually push a tag and then increment the dev version to 0.2.0-SNAPSHOT.
* And backports will be maintained in a branch 0.1, or 0.1.x branch.

0.2.x can then include the api changes in #53

**Comment by woop** [comment]
Let's reopen this issue once we release 0.3.0
