### ISSUE TITLE
How does Feast handle feature creation?

### ISSUE THREAD

**Issue by woop** [gojek/feast#75]
Since this will be an important topic to cover, I thought it would be wise to create an issue where we could both explain and discuss how feature creation fits in to Feast.

The current state is that feature creation is left up to the producer of features. Feast allows these features to be ingested for training and serving, but the act of engineering features is left to upstream processes. Feast does support referring to feature transformation code from feature specifications.

The question then becomes, how are users able to trace features that are ingested back to raw data sources? What would be the standard approach to engineering this upstream system and how do feature specifications connect to code and data?

**Comment by MrSaints** [comment]
Interesting topic. For traceability / audit trail, I can appreciate the need to link features back to their origin. From practical use-cases, it does not seem quite clear. That is, what are the core problems that it is trying to solve?

Looking briefly at notes on Uber's Michaelangelo (which has a similar shared feature store):

> It allows users to easily add features they have built into a shared feature store, requiring only a small amount of extra metadata **(owner, description, SLA, etc.)** on top of what would be required for a feature generated for private, project-specific usage.

Perhaps it is best to leave the existing `uri` specification to the end-user. For example, it can be their own ARN-inspired URN, and they can handle the responsibility of keeping track of feature creation, thereby reducing the possibility of feature creep in this project.
Alternatively, in lieu of the lack of authentication / authorisation, maybe there can be a client ID (in the same way there are multiple data stores). But this seems too loose a specification.

**Comment by woop** [comment]
Just to address this again. For 0.3.0 feature creation will still remain upstream from Feast.
